### PR TITLE
Update header design and navigation

### PR DESCRIPTION
**Pull request by annagav**
# What are the relevant tickets?
Partially completes https://github.com/mitodl/hq/issues/2559

# Description (What does it do?)
1. Change the anonymous header to use hamburger menu
2. Add Catalog link to the anonymous desktop header
3. Adds Catalog link to the dropdown navigation

# How can this be tested?
Checkout the header in desktop, mobile, anonymous, authenticated views. Make sure the navigation works.

# Screenshots (if appropriate):
Mobile View:

Screen Shot 2023-11-01 at 8 48 52 AM

Screen Shot 2023-11-01 at 8 11 48 AM
Screen Shot 2023-11-01 at 8 21 02 AM
Desktop:

Screen Shot 2023-11-01 at 8 17 59 AM
Screen Shot 2023-11-01 at 8 20 15 AM

Screen Shot 2023-11-01 at 8 34 49 AM

### CODE REVIEW

**Comment by mbilalmughal** [comment]
@annagav Two things only

- Mobile links should be "white" not red - See Attachment 1
- The catalog link should be outside of the profile menu, as you already did in one of the screenshots above - See attachment 2

image

image

**Comment by annagav** [comment]
After addressing Bilal's feedback:
Screen Shot 2023-11-01 at 10 22 27 AM
Screen Shot 2023-11-01 at 10 13 07 AM

**Review by rachellougee — COMMENTED** [review]
One issue I noticed is when I click on any of these links on mobile without logging in, the menu overlap doesn't close automatically and block the page unless I click on x. Is that expected? It doesn't happen when I logged in though
image

**Review by rachellougee — APPROVED** [review]
LGTM. Overlay issue is resolved on mobile

**Pull request merged**
