### PR TITLE
Adds additional demographic fields to the system; adds popup to collect more data when visiting a course

### LINKED ISSUE #1424: Profile: Pop-up request for optional profile information
part of #1398 

As a marketing team member, I'd like to collect optional profile information to target marketing messages better. 

As an educational researcher, I'd like to know more about our users to improve research and analysis. 

As a user, I don't want to share more information unless I know what value I'm getting for it. 

### description 

When the user take an action that demonstrates interest in the platform, like enrolling in a course, we will display a form that requests additional, optional profile information. We'll only show this once, even if the user has chosen not to fill out any of the additional fields. 

### acceptance criteria 

- [ ] pop-up form when a user visits a course from their dashboard
- [ ] include an introduction: "To help us with our educational research missions, please tell us more about yourself"
- [ ] only show the pop-up once (if they user wants to change their data, they can use the profile page) 
- [ ] basic, optional fields:
  - [ ] Gender Identity (choose one)
     - Woman
     - Man
     - Transgender
     - Non-binary / non-conforming
     - Prefer not to respond 
  - [ ] Highest level of education: choose one, [same values as xPRO](https://github.com/mitodl/mitxpro/blob/b6305e2b60bb335fd99bb7ed4905d16462419642/static/js/constants.js#L98-L108)
  - [ ] user type:
     - label: "Are you a: "
     - values: student, professional, educator, other
     - multi-select
- [ ] if user-type includes "professional" display additional fields
   - [ ] Company: (free text)
   - [ ] Job Title: (free text) 
   - [ ] Industry: same values as xPRO
   - [ ] Function: same values as xPRO
   - [ ] Company size: same values as xPRO
   - [ ] Years of experience: same values as xPRO
   - [ ] Leadership Level: same values as xPRO
- [ ] include a note at the end "You can update this information anytime in your User Profile."

### PR DESCRIPTION
**Pull request by jkachel**
#### Pre-Flight checklist

- [X] Screenshots and design review for any changes that affect layout or styling
  - [X] Desktop screenshots
  - [X] Mobile width screenshots
- [X] Migrations
  - [X] Migration is backwards-compatible with current production code
- [X] Testing
  - [X] Code is tested
  - [X] Changes have been manually tested
- [X] Settings
  - [X] New settings have reasonable development defaults, if applicable
  - [ ] Opened issue for DevOps regarding necessary configuration changes to deployed environments

#### What are the relevant tickets?

Closes #1424 

#### What's this PR do?

Adds a number of demographic data fields to the user profile. These expose the fields added to the database in [#1443](https://github.com/mitodl/mitxonline/pull/1443). 

Adds a popup requesting more data from the learner when they attempt to navigate to a course. This popup only occurs once and includes a form that has the new fields from #1443 and the Gender and Year of Birth fields. 

Adds a utility function to the front end code that should make working with feature flags easier in the future. 

#### How should this be manually tested?

Automated tests should pass.

All new UI elements are hidden behind a feature flag - set `FEATURE_ENABLE_ADDL_PROFILE_FIELDS` to True in your .env file to test. Alternatively, append `?enable_addl_profile_fields` to the URL on the dashboard and profile pages to see the changes. 

Testing profile form:
1. Log in as a user. 
2. Navigate to the profile page.
3. Observe the fields there. You should see now a set of checkboxes listed - one each for Educator, Professional, Student, and Other. None of them should be required.
4. Checking them and saving should work.
5. Checking Professional should expand the form to include: 
   * Company
   * Job Title
   * Industry
   * Job Function
   * Company Size
   * Years of Work Experience
   * Leadership Level
   * Highest Level of Education
6. Filling out these fields should work.

Testing popup:
You will need a user that's enrolled in a course (enrollment mode doesn't matter here; they just need to be enrolled at all). 
1. In a separate tab, open the Django Admin and find the user you're testing with. Open the User Profile section and observe the status of the `Addl field flag` field. 
2. _If the flag is set_: navigate to the user's dashboard and click the title of a course to open the course homepage. This should work as expected.
3. _If the flag is **un**set_: navigate to the user's dashboard and click the title of a course to open the course homepage.
   1. Reloading the user's record in the Django Admin should now show the flag is set. 
   2. A "Provide more info" dialog should appear, requesting more information. The fields should be Gender, Year of Birth, and "Are you a". The Professional checkbox should show and hide the additional company information as it does on the Profile page.
   3. Clicking Save should save the information into the profile and continue on to open the course homepage. Note that since the dialog will do this programmatically, your browser may block the popup. 

#### Screenshots (if appropriate)
Edit Profile (Professional not checked):
image

Edit Profile (Professional checked):
image

More Info dialog (Professional not checked):
image

More Info dialog (Professional checked):
image

More Info dialog (Professional checked; on mobile):
image

Edit Profile (Professional checked; on mobile):
image

### CODE REVIEW

**Review by collinpreston — APPROVED** [review]
Looks good and works for me.  I was able to view the additional fields on the profile page without the use of the environment variable or `?enable_addl_profile_fields`.

**Comment by jkachel** [comment]
> I was able to view the additional fields on the profile page without the use of the environment variable or `?enable_addl_profile_fields`.

well that's no good.. fixed it in https://github.com/mitodl/mitxonline/pull/1449/commits/e5a9c9eea136c3879475949d366a215f3c13601b

**Review by collinpreston — CHANGES_REQUESTED** [review]
I am receiving an error when using the `?enable_addl_profile_fields`: 
Screenshot 2023-02-28 at 13 23 52

Should gender and year of birth be displayed if `?enable_addl_profile_fields` and the environment variable are not set?

**Comment by jkachel** [comment]
Good catch - after looking it seems like the account you're using locally doesn't have a UserProfile record. https://github.com/mitodl/mitxonline/pull/1449/commits/ba1495eff6a3cd01b6306f9128a2c21e0af5061f adds a migration to backfill those.

**Review by collinpreston — APPROVED** [review]
Approved

**Pull request merged**
