### PR TITLE
fixes Ecommerce: Accessibility: Discount code error message is invisible to screen reader

### LINKED ISSUE #517: Ecommerce: Accessibility: Discount code error message is invisible to screen reader
### Steps to Reproduce

- Using a screen reader, from the checkout page, enter an invalid discount code
- Click apply

### Expected Behavior

- Focus would shift to the error message
- It would be read by the screen reader

### Actual Behavior

- The user isn't aware that there is an error

### Screenshot or Screencast

image

### PR DESCRIPTION
**Pull request by umarmughal824**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
fixes #517 

#### What's this PR do?
fixes Ecommerce: Accessibility: Discount code error message is invisible to screen reader

#### Screenshots (if appropriate)
Screenshot 2022-04-21 at 16 52 09
Screenshot 2022-04-21 at 16 54 10
Screenshot 2022-04-21 at 16 54 19
Screenshot 2022-04-21 at 17 20 35
Screenshot 2022-04-21 at 17 21 08
Screenshot 2022-04-21 at 17 22 09
Screenshot 2022-04-21 at 17 22 19

### CODE REVIEW

**Comment by umarmughal824** [comment]
@jkachel could you please review the PR?

**Review by jkachel — APPROVED** [review]
LGTM 👍

**Comment by umarmughal824** [comment]
@briangrossman could you please take a look at the attached screenshots and let me know if you have any concerns?

**Comment by briangrossman** [comment]
The screenshots look good to me.

**Pull request merged**
