### PR TITLE
Pre commit linting

### PR DESCRIPTION
**Pull request by blarghmatey**
### What are the relevant tickets?
N/A

### Description (What does it do?)
Adds comprehensive pre-commit checks to match our other projects as a follow-on to https://github.com/mitodl/hq/discussions/1422 and https://github.com/mitodl/hq/discussions/2993

### How can this be tested?
Install the pre-commit utility via poetry and run `pre-commit run --all-files`

### CODE REVIEW

**Comment by pdpinch** [comment]
Is there any way we can break this into pieces?

**Comment by blarghmatey** [comment]
I updated this PR to exclude everything related to frontend code for now. I can work with someone on that piece when I get back from vacation.

**Review by JenniWhitman — DISMISSED** [review]
Ran through files looking for anything it changed that was obviously more than formatting or slight changes, don't see anything that would cause any major functional changes. Ran tests, manually tested functionality, and rebuilt my containers to be sure things ran smoothly.

I don't see any issue - mostly we're looking at EoL additions, old string formatting, unused imports, and some noqa additions to make black run without anger.

**Comment by JenniWhitman** [comment]
I take that back, auto migrations are failing on ci
let me see

**Review by JenniWhitman — APPROVED** [review]
Still works, now with more passing tests :)

**Pull request merged**
