### PR TITLE
changed background color

### PR DESCRIPTION
**Pull request by Wassaf-Shahzad**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
- [x] Testing
  - [X] Changes have been manually tested

#### What are the relevant tickets?
ticket #142 

#### What's this PR do?
Changes the background color to #f5f5f5

#### How should this be manually tested?
Visit SignIn page and verify background colour is #f5f5f5
Visit course page and verify background colour is #f5f5f5

#### Screenshots (if appropriate)
Screenshot 2021-09-02 at 5 29 35 PM

Screenshot 2021-09-02 at 5 29 16 PM

### CODE REVIEW

**Comment by pdpinch** [comment]
Screenshots look good, but the issue was to standardize the background. Are there any other pages that have the wrong background?

**Comment by Wassaf-Shahzad** [comment]
> Screenshots look good, but the issue was to standardize the background. Are there any other pages that have the wrong background?

So the home page, dashboard, account and auth pages had linear gradient backgrounds. I specified the the background colour in the layout.scss and it should apply to all pages.

**Review by arslanashraf7 — CHANGES_REQUESTED** [review]
Although it works fine for most of the pages e.g. Registration, Auth, Home, Dashboard, settings but the behavior is incorrect for the Product Detail Page as follows:

1) The background of the `Product Detail Page` is still solid white (Can be seen in your PR screenshot as well), Note that the white background change was intentional and it was part of the requirements of another ticket https://github.com/mitodl/mitxonline/issues/91. I believe the invasion design was updated later on once again.

2) Now, When you'll remove [this line](https://github.com/mitodl/mitxonline/blob/main/static/scss/product-details.scss#L4) to overide the `layout.scss` color in Product Detail Page, you'll see something like below image which based on invasion design is also incorrect
Screenshot 2021-09-03 at 3 14 37 PM

3) So, to match the design with [Invision Design](https://projects.invisionapp.com/d/main/#/console/21535972/455477372/preview) you will need to do point#2 and add the support for white background on course properties as below:

Screenshot 2021-09-03 at 3 17 01 PM

CC: @pdpinch in case you'd like to add any comment.

**Comment by pdpinch** [comment]
Thanks for catching this Arslan. This is the correct styling: 

> 
> So, to match the design with Invision Design <https://projects.invisionapp.com/d/main/#/console/21535972/455477372/preview> you will need to do point#2 and add the support for white background on course properties as below:
>  <https://user-images.githubusercontent.com/34372316/131990115-c2396267-ab50-4c85-bda1-1c6cbb5c6424.png>
>

**Comment by pdpinch** [comment]
FYI, @asadiqbal08 also has a PR https://github.com/mitodl/mitxonline/pull/126#issuecomment-912513243 that updates the course detail page. You should coordinate with him to avoid any conflicts.

**Comment by asadiqbal08** [comment]
I have done the changes related to `tiles`, that I can merge if you guys are ok https://github.com/mitodl/mitxonline/pull/126#issuecomment-912513243

**Review by arslanashraf7 — APPROVED** [review]
👍

**Pull request merged**
