### PR TITLE
4545 mitx online program drawercourse upgrade formatting

### PR DESCRIPTION
**Pull request by collinpreston**
### What are the relevant tickets?
https://github.com/mitodl/hq/issues/4545

### Description (What does it do?)
Fixes the upgrade button formatting on the program drawer

### Screenshots (if appropriate):
Screenshot 2024-06-14 at 8 10 12 AM

### How can this be tested?

1. Enroll into a program.
2. Go to your dashboard, then program tab, then click on the program.
3. Verify that the "Get certificate" button is formatted under the text for any required course.
4. Verify that the formatting of the same button is unchanged when viewing the course on the course tab of the dashboard.

### CODE REVIEW

**Review by annagav — CHANGES_REQUESTED** [review]
I think the button is supposed to be aligned on the right:

Screenshot 2024-06-14 at 9 50 32 AM

**Comment by annagav** [comment]
Looks good! Just one minor thing: could we put "Get Certificate" text in the button into one line?
Screenshot 2024-06-17 at 9 40 40 AM

**Comment by collinpreston** [comment]
> Looks good! Just one minor thing: could we put "Get Certificate" text in the button into one line? Screenshot 2024-06-17 at 9 40 40 AM

I tried resolving this, but it seems that the button text is two lines due to padding and the size of the font when the page is in a medium sized viewport.

**Comment by collinpreston** [comment]
> > Looks good! Just one minor thing: could we put "Get Certificate" text in the button into one line? Screenshot 2024-06-17 at 9 40 40 AM
> 
> I tried resolving this, but it seems that the button text is two lines due to padding and the size of the font when the page is in a medium sized viewport.

@mbilalmughal do you know how the text on this button should be formatted?

**Comment by annagav** [comment]
@mbilalmughal Could you help us find the UI design for this view?

**Review by annagav — APPROVED** [review]
👍

**Pull request merged**
