### PR TITLE
fix: program certificate link text

### PR DESCRIPTION
**Pull request by aliraza-abbasi**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Migrations
  - [ ] Migration is backward-compatible with the current production code
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable
  - [ ] Opened issue for DevOps regarding necessary configuration changes to deployed environments

#### What are the relevant tickets?
#1264 

#### Screenshots (if appropriate)
Screenshot 2022-12-14 at 2 45 22 PM
Screenshot 2022-12-16 at 6 50 31 PM

### CODE REVIEW

**Comment by aliraza-abbasi** [comment]
@pdpinch I had already added the view certificate link if the `program certificate`, `program page`, and `program certificate page` is available. Just updated the text. Don't we need to add other design changes here in this ticket? I have done some work on new changes according to the new `ProgramRequirement` model. But then I realized this ticket only required a link only.

**Comment by pdpinch** [comment]
I’m not sure what design changes you have in mind. Can you be more
specific?

**Comment by aliraza-abbasi** [comment]
> I’m not sure what design changes you have in mind. Can you be more specific?
> […](#)

The design link here which includes `Program passed` text and other text changes
https://projects.invisionapp.com/d/#/console/21535972/470593814/comments

And for second question I found it's related ticket #1220  which will solve the problem

**Comment by pdpinch** [comment]
Thanks for the invision link. Please add a "program completed" tag (similar to the "course passed" tag). I think we should leave the rest for other issues.

**Review by annagav — APPROVED** [review]
Looks great 👍

**Pull request merged**
