### PR TITLE
asadiqbal08/Added Approve and Reset button to Refine Admin

### PR DESCRIPTION
**Pull request by asadiqbal08**
#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots\
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
fixes: #576 
fixes: #577 

#### What's this PR do?

PR added some front end logic for approving and resetting the flexible pricing from Refine Admin portal. A button to approve / Reset the flexible pricing option.

The statuses in the app are created, approved, auto-approved, denied, and reset. reset allows the learner to re-request flexible pricing for the given course/program.

#### How should this be manually tested?
Visit: `/flexible_pricing/` endpoint and approve and reset the status.

#### Screenshots (if appropriate)
screencapture-mitxonline-odl-local-8016-flexible-pricing-2022-06-02-13_37_48

Video Demo --> https://watch.screencastify.com/v/8TLuJL6h6fMSOZthohvJ

### CODE REVIEW

**Comment by asadiqbal08** [comment]
@jkachel @pdpinch can you please share thoughts about the UI changes for approving and resetting flexible pricing from Refine Admin portal as I did in this PR ? 

A demo video is added up here https://watch.screencastify.com/v/8TLuJL6h6fMSOZthohvJ

**Comment by jkachel** [comment]
Haven't done the code review yet but the screencast looks good to me. We will probably want to change some of the copy in the modals and toasts but will defer to @pdpinch on that. I'm also not sure about the undo functionality - I like it but we also have the confirmation modal. That flow would be handy to have elsewhere too.

**Comment by pdpinch** [comment]
Sorry, the screen cast has confused me.

There are two Flexible Pricing Requests from the same user. How is that possible?

What are the possible values for status? 

What does a status of "reset" mean, exactly? 

Sorry if these questions are out of scope for this PR, but answers would help me understand the flow better in this PR>

**Comment by jkachel** [comment]
The requests are tied to the course/program specifically. That's not exposed in the UI, though. It should be displayed but that should be a different issue, I think.

The statuses in the app are created, approved, auto-approved, denied, and reset. `reset` allows the learner to re-request flexible pricing for the given course/program.

**Comment by asadiqbal08** [comment]
@pdpinch I guess @jkachel has clarified about the statues regarding this

> There are two Flexible Pricing Requests from the same user. How is that possible?

I added manually flexible prices via using Django Admin for testing so you can ignore those items yet. The purpose of these buttons is to update the status in flexible pricing model accordingly.

**Comment by asadiqbal08** [comment]
@pdpinch I guess @jkachel has clarified about the statues regarding this

> There are two Flexible Pricing Requests from the same user. How is that possible?

I added manually flexible prices via using Django Admin for testing so you can ignore those items yet. The purpose of these buttons is to update the status in flexible pricing model accordingly.

**Comment by pdpinch** [comment]
This is a pretty big change from the existing functionality at `/financial_aid/review/2`

Again, these questions may be out of scope for this PR. I'm not sure all these legacy MM features are necessary. But I'd like to know what the plan is for them (if there is one). 

- How does the admin deny the financial aid request? 
- I think it would be helpful for the admin to see the discount in this view (whether expressed as a percent off, or a final price). 
- How/can the admin user change the discount?
- When changing the status in MM, the admin must select a "justification" (See https://github.com/mitodl/micromasters/blob/7546f4e962bd65b5a341351bf47f411b3d9d9084/financialaid/constants.py#L9-L19). Is that part of the model here?

**Pull request merged**
