### PR TITLE
fix(Accessibility): added missing SITE_NAME to context to fix head titles

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
#148 

#### What's this PR do?
- Adds the missing `SITE_NAME` config variable from the Django templates
- Fixes the head titles of the pages using the site name

#### How should this be manually tested?
- Visit the home page of the web and see the head title is the one set in the `SITE_NAME` variable 
- Visit the product page and check that the head title is `{Page Name} | {Site Name}`
- Generally, other pages could also be checked to verify this change

#### Where should the reviewer start?
Home Page

#### Screenshots (if appropriate)
**Note:** For the **Before** screenshot you can visit the associated ticket

**Home Page Head**
Screenshot 2021-09-07 at 4 54 01 PM

**Product Page Head**
Screenshot 2021-09-07 at 4 53 50 PM

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@pdpinch Can you take a look at the screenshots and let me know if you approve of them or you'd like to see any changes.

**Review by asadiqbal08 — APPROVED** [review]

**Comment by pdpinch** [comment]
Screenshots look good. I presume this addresses all the pages managed in Wagtail. Do the other pages need titles, like the dashboard and the signin/account creation?

**Comment by arslanashraf7** [comment]
> Screenshots look good. I presume this addresses all the pages managed in Wagtail. Do the other pages need titles, like the dashboard and the signin/account creation?

Those are managed through React and they already have the titles in place so they were already working. e.g. below screenshot.
Screenshot 2021-09-08 at 5 41 40 PM




**Although** I noticed a small text difference on Create Account on RC, where the tab title is `Register` and our button/page title is `Create Account`. This could or couldn't be an issue since we are using `Register` tab title for our whole Create Account flow. Screenshot below:
Screenshot 2021-09-08 at 5 47 37 PM

**Comment by arslanashraf7** [comment]
@pdpinch, Based on the above conversation it makes sense to merge this PR, And if there are any concerns regarding the details that I added in the above comment, we should do it in a separate PR anyway.

**Pull request merged**
