### PR TITLE
feat: add search and filters on Discount admin model

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [ ] Mobile width screenshots
- [x] Testing
  - [ ] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
#1380 

#### What's this PR do?
- Adds search filter for discount code in Discount admin model
- Adds list filter for `discount_type` and `redemption_type`, `for_flexible_pricing` in Discount Django Admin model

#### How should this be manually tested?
- Setup this branch
- Verify that you can search discounts based on `discount_code`
- Verify that filters (`discount_type`, `redemption_type`) work fine

#### Screenshots (if appropriate)
Screenshot 2023-01-25 at 6 23 36 PM

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@pdpinch I've added a coupon code-based search along with `Coupon Type` and `Redemption Type` based filters as seen in the attached screenshot in the PR description. 

Let me know if you'd like to add more filters or require any changes in search.

**Review by asadali145 — APPROVED** [review]
LGTM!

**Comment by pdpinch** [comment]
Please add a filter for the flexible price boolean.

**Comment by arslanashraf7** [comment]
> Please add a filter for the flexible price boolean.

Added in https://github.com/mitodl/mitxonline/pull/1381/commits/d42ca0a0be25d062f4be49a44857bd8f81cc4344. Also updated the screenshot.

**Comment by arslanashraf7** [comment]
Merging this, Since it the new change is pretty straight forward.

**Pull request merged**
