### PR TITLE
fix: limit user full name to 255 characters

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### Pre-Flight checklist

- [x] Migrations
  - [x] Migration is backwards-compatible with current production code
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
#1438 

#### What's this PR do?
- Limits user's full name to have a max of 255 characters
- changes user name filed from Text to Char
- Adds 255 character limit to user profile form on the frontend
- adds a migration to trim existing full names longer than 255 characters

#### How should this be manually tested?
- Setup on master and create an account that has a full name containing more than 255 characters
- Shift to this branch, build and run the containers again, and make sure the new migration runs successfully and it trims the full name in the above point to 255 characters
- Register a new account, and check that you see a validation error message for the `Full Name` when you enter more than 255 characters

#### Where should the reviewer start?
- Setup on master, register an account

#### Screenshots
**Before**
image

**After**
image

image

### CODE REVIEW

**Review by asadali145 — APPROVED** [review]
LGTM!

**Comment by arslanashraf7** [comment]
@pdpinch Could you also take a look at mostly the design part? When the user's full name was very long it would break the UI. The issue was noted in https://github.com/mitodl/mitxonline/issues/1438. In this PR I have limited the display limit of the name to `40 characters` at max with extra text to use an ellipsis (Screenshot attached in PR description). 
Let me know what you feel about this.

**Comment by pdpinch** [comment]
> In this PR I have limited the display limit of the name to 40 characters at max with extra text to use an ellipsis 

This is a good approach. How did you decide on 40 characters?

How many characters are visible when the user sets their full name in the profile form?

**Comment by arslanashraf7** [comment]
> > In this PR I have limited the display limit of the name to 40 characters at max with extra text to use an ellipsis
> 
> This is a good approach. How did you decide on 40 characters?

This limit seemed reasonable enough and looked fine. How this looks with 40 characters, There is a screenshot in the PR description. We can change this too, let me know if you want to try some other limits and i can get their screenshots for you.

> 
> How many characters are visible when the user sets their full name in the profile form?

In the profile form, all the characters would be visible, The display change only affects the name in the header.

**Comment by arslanashraf7** [comment]
The name in the profile form looks like below and it's horizontally scrollable within the field, if that's what you meant in your question.

image

**Pull request merged**
