### PR TITLE
Fix catalog page for empty app

### PR DESCRIPTION
**Pull request by collinpreston**
### What are the relevant tickets?
NA

### Description

1. Removes a bunch of unused or duplicate code.
2. Refines logic and methods to be more single-purpose/functional.
3. Allows for Program + department URLs such as http://mitxonline.odl.local:8013/catalog/programs/science
4. Resolves and issue where https://rc.mitxonline.mit.edu/catalog/programs loads an empty catalog page.

### How can this be tested?

1. Verify that you can navigate the catalog page for both courses and programs, switching between departments, switching between tabs, and loading more courses and programs as you scroll.
2. Verify that you can navigate to the course and program tab using a URL such as http://mitxonline.odl.local:8013/catalog/programs/
3. Verify that you can navigate to the course and program tab, and filter by department, using a URL such as http://mitxonline.odl.local:8013/catalog/programs/science
4. Accessibility of the catalog page should not change.

### CODE REVIEW

**Comment by annagav** [comment]
@collinpreston this branch has conflict with main

**Comment by collinpreston** [comment]
> @collinpreston this branch has conflict with main

@annagav I've merged this branch with the main branch.

**Comment by annagav** [comment]
I am seeing something, that might be a bug:

I select a department that has no propgrams `Department test 1`
Screenshot 2024-04-11 at 8 35 57 AM

Then I click on programs tab. It shows me the programs correctly but the url stays with the previous depeartment selection:
Screenshot 2024-04-11 at 8 35 38 AM

**Comment by annagav** [comment]
The previous problem is fixed 👍 

Now when I nuvigate to programs/test-department-1, which has no programs it just shows me the programs tab, and the department ends up unselected.

Screenshot 2024-04-11 at 10 59 06 AM

**Pull request merged**
