### PR TITLE
Give priority to enrollable runs

### PR DESCRIPTION
**Pull request by annagav**
### What are the relevant tickets?
Fix https://github.com/mitodl/hq/issues/4146, https://github.com/mitodl/hq/issues/4197, https://github.com/mitodl/hq/issues/4199

### Description (What does it do?)
When only archived run is enrollable it has priority of coming up future runs.

This PR changes the logic for firstRelevantRun:
1. If there are enrollble runs - choose the one that is closest to now, giving preference to runs that start in the future.
2. If there are no currently enrollable runs, then return a run that will be enrollable in future
3. If there are no enrollable now and enrollable in future runs than return null. When this happens the "Enroll Now" button will be grey and disabled with the text "Access Course Materials".

### Screenshots (if appropriate):
Screenshot 2024-05-10 at 7 45 08 AM

Screenshot 2024-05-09 at 1 07 24 PM

### How can this be tested?
Create a run the has an enrollable archived course and a run in the future like this course in production: https://mitxonline.mit.edu/courses/course-v1:MITxT+24.10x/ (you must be logged in to see that the enroll button is missing)

When you change to this branch the enroll now button should show up and open a dialog when clicked.

### CODE REVIEW

**Comment by cachob** [comment]
@annagav / @JenniWhitman / @collinpreston / @jkachel - I got word from Peter that we need this released ASAP and we can release today (Friday) if possible

**Comment by JenniWhitman** [comment]
I just put up https://github.com/mitodl/mitxonline/pull/2200 to address the failing test. Am finishing the review now.

**Comment by JenniWhitman** [comment]
In the meantime, I'm re-running the python tests since those failures are random

**Review by JenniWhitman — CHANGES_REQUESTED** [review]
Everything works as I expect except if I have a past run, a future run (not open for enrollment) the enroll now button is just gone. Is this expected?

**Comment by annagav** [comment]
This PR is no longer urgent since we fixed the particular issue by updating the course run manually. So this can wait till monday.

**Comment by annagav** [comment]
I found another course without enrollment button https://mitxonline.mit.edu/courses/course-v1:MITxT+18.01.1x/

**Review by JenniWhitman — APPROVED** [review]
Works as expected now

**Pull request merged**
