### PR TITLE
Flexible pricing: updates income form

### LINKED ISSUE #709: Flexible pricing: update income form
#### Designs and Mockups

See [https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468433645](https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468433645/preview)

#### Acceptance Criteria:

- [ ] take a look at the design and let us know if the form responses being outside the card will be a problem
- [ ] The checkbox is a required field, but doesn't require storing any data.

### PR DESCRIPTION
**Pull request by umarmughal824**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
fixes #709 

#### What's this PR do?
Flexible pricing: updates income form

#### Screenshots (if appropriate)
Screenshot 2022-07-28 at 3 36 15 PM
Screenshot 2022-07-28 at 3 36 45 PM
Screenshot 2022-07-28 at 3 36 57 PM
Screenshot 2022-07-28 at 3 37 33 PM
Screenshot 2022-07-28 at 3 38 08 PM
Screenshot 2022-07-28 at 3 38 22 PM
Screenshot 2022-07-28 at 3 38 45 PM
Screenshot 2022-07-28 at 3 38 55 PM
Screenshot 2022-07-28 at 3 39 11 PM
Screenshot 2022-07-28 at 3 39 22 PM
Screenshot 2022-07-28 at 3 39 58 PM
Screenshot 2022-07-28 at 3 40 10 PM
Screenshot 2022-07-28 at 3 40 25 PM

### CODE REVIEW

**Comment by umarmughal824** [comment]
@pdpinch I am assigning this to @asadali145 that he needs to carry it further. I will help him out along the way. The progress is form design is complete just need the design of the out section.

**Review by jkachel — CHANGES_REQUESTED** [review]
I don't see the headings anywhere - for example, https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468433646/preview has a `h1` that'll need to be in the template.

**Comment by asadali145** [comment]
> I don't see the headings anywhere - for example, https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468433646/preview has an `h1` that'll need to be in the template.

@jkachel Thanks for the review.

1. Headings and paragraphs for these pages are handled from CMS, both the heading and the paragraph will be added in the RichTextFields i.e. application_processing_text, application_approved_text, and application_denied_text.
2. I haven't used `h1` in the template because the CMS is handling both and we have a single field for that. You can check the screenshots. Let me know if we still want to make changes.
3. Also, I have one doubt, In the screenshots attached to the ticket, I have used `h2`.
4. In `FlexiblePricingRequestForm`, we are using the default features of a RichTextField which includes `h1` but I cannot see `h1` in the editor interface options. [Docs](https://docs.wagtail.org/en/stable/advanced_topics/customisation/page_editing_interface.html#limiting-features-in-a-rich-text-field) clearly mention that the `h1` is a part of default features of a RichTextField. In the attached SS, you can see there is no `h1` option. We can still add `h1` as a RichTextField feature. Let me know if we want to add `h1` as a feature.

Let me know if you have any other doubts, questions, or suggestions.

Screenshot 2022-07-28 at 10 42 01 AM

**Comment by asadali145** [comment]
> I don't see the headings anywhere - for example, https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468433646/preview has an `h1` that'll need to be in the template.

@jkachel Please re-review the PR. I have added an option in CMS to add `h1` in a rich text field. Let me know if there are any other suggestions.

**Comment by jkachel** [comment]
Ok. Do we want the headings to be defined in the CMS? It kinda feels like something that should be set in the template (at least for consistency). I'm open to suggestions here, though. @pdpinch thoughts?

**Comment by asadali145** [comment]
Now all the headings including Application Updates and the form headings and text will be defined in CMS. So, It is consistent in a way that whole content is added from CMS. Open to suggestions and can make changes to the template if required.

**Review by jkachel — APPROVED** [review]
LGTM 👍

**Pull request merged**
