### PR TITLE
style: add support footer

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
#188 

#### What's this PR do?
- Adds support footer

#### How should this be manually tested?
- Check that you can see the support footer as mentioned in ticket #188 
- Check that it's visible on all the pages

#### Where should the reviewer start?
- Home Page

#### Screenshots (if appropriate)
**Desktop**
screencapture-mitxonline-odl-local-8013-2022-01-19-12_51_49

**Mobile**
screencapture-mitxonline-odl-local-8013-2022-01-13-18_35_55

**Tablet**
screencapture-mitxonline-odl-local-8013-2022-01-13-18_59_53

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@pdpinch Can you take a look at the screenshots and let me know if they look good.

**Comment by pdpinch** [comment]
Not sure how this is implemented in xPRO, but in desktop views there is a limit to how far apart the "Help & FAQ" and "Contact Us" logos will adjust to the left and right. It's not a big deal, but if you can do the same here I think it will look better. 

Compare: 
image

**Comment by arslanashraf7** [comment]
@pdpinch I actually intentionally did it keeping in mind that we should keep the screen container width uniform overall. Since we have different container width in xPRO and MITxOnline so I adjusted `Contact Us & About` based on the container width of the overall MITxOnline web app. (I attached some screenshots below regarding the container width)

However, I'll change it as you mentioned.

Compare:
mitxonline-desktop
xpro-desktop

**Comment by arslanashraf7** [comment]
@pdpinch In addition to the last comments, I tweaked the support footer design as per xPRO and I'm adding a screenshot of how it looks now.
So, In any case, if you would like to go with the below design,  I'll commit them to the PR **_OR_** based on my above comment if you'd like to follow the container width, which is already done in the PR. Let me know what you think.

screencapture-mitxonline-odl-local-8013-2022-01-17-12_48_06

**Comment by pdpinch** [comment]
I see. Does the container on xPRO have a max width? Maybe we should give the container on mitxonline a maximum width. 

If that sounds reasonable, I'm fine with merging this as is if you can open a follow-up PR to modify the container width.

**Comment by arslanashraf7** [comment]
@pdpinch,

> I see. Does the container on xPRO have a max width? Maybe we should give the container on mitxonline a maximum width.

Yes, the container on xPRO works with a max-width property, And I've set max-width support (footer only) with max-width as well. Desktop screenshot updated in the PR description however, mobile and tablet screenshots remain unaffected.

> If that sounds reasonable, I'm fine with merging this as is if you can open a follow-up PR to modify the container width.

I've updated the container width for support footer to a max-width as xPRO, The global container(Header, Main Footer, etc) for MITxOnline remains the same as it should have been.

@annagav This PR is ready for review.

**Review by annagav — APPROVED** [review]
LGTM👍

**Comment by briangrossman** [comment]
Opened the browser to give it a test,
Knowing full well that @arslanashraf7  is the best,
Took a look at the pages on RC,
As expected, looks good to me 👍

**Pull request merged**
