### PR TITLE
Home Page Hero Component

### PR DESCRIPTION
**Pull request by JenniWhitman**
# What are the relevant tickets?
updates https://github.com/mitodl/hq/issues/1677

# Description (What does it do?)
This is a redesign of the Hero component on the mitxonline home page. This redesign will also make the text on the page static/part of the template. This includes both mobile and desktop views as available in the figma. There is a feature flag keeping this from showing outside of dev.

# Screenshots (if appropriate):
Desktop View
Mobile View

# How can this be tested?
Load up the branch in an environment where environment = dev and set up for posthog use with environment variables. You should get the new hero view.  Toggle the flag in posthog to off to make sure the old view still works otherwise.

# Additional Context
flag = [mitxonline-new-featured-hero](https://app.posthog.com/feature_flags/15990)
[Figma](https://www.figma.com/file/Gs4zIhOFv5gVvafawwl6PF/MITx-Online?type=design&node-id=558%3A2716&mode=dev)

### CODE REVIEW

**Review by annagav — CHANGES_REQUESTED** [review]
@JenniWhitman I can see the changes for the home page, but the course page looks broken for me.

**Comment by JenniWhitman** [comment]
> @JenniWhitman I can see the changes for the home page, but the course page looks broken for me.

Whoops - good catch. Should be fixed. Accidentally deleted it from style.js on merge.

**Comment by annagav** [comment]
The hero image and the courses carousel do not fill the width of the page like in the styles:
Screen Shot 2023-08-28 at 3 09 44 PM

**Review by annagav — APPROVED** [review]
LGTM 👍

**Pull request merged**
