### PR TITLE
Implement basic site footer content

### LINKED ISSUE #18: Implement basic site footer content
Design: https://projects.invisionapp.com/share/KH11D3ZN53GC#/screens/455535008 (featured on all pages)

**Acceptance criteria:**
- Footer appears on all pages
- Footer contains logo and all relevant text, and matches the designs at all screen widths

**Not needed:**
- Working links to the resource pages (about us, terms of service, etc.)
- "Sign up" text input and button (this section can be left out completely

### PR DESCRIPTION
**Pull request by umarmughal824**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
fixes #18 

#### What's this PR do?
Implement basic site footer content 

#### How should this be manually tested?
Just visit the footer of the page

#### Screenshots (if appropriate)
Screenshot 2021-07-29 at 17 34 32
Screenshot 2021-07-29 at 17 34 51
Screenshot 2021-07-29 at 17 35 00
Screenshot 2021-07-29 at 17 35 12
Screenshot 2021-07-29 at 17 35 23
Screenshot 2021-07-29 at 17 35 48
Screenshot 2021-07-29 at 17 35 56

### CODE REVIEW

**Comment by pdpinch** [comment]
Screenshots look good. You can get a [PNG of the logo from InVision](https://projects.invisionapp.com/assets/21535972/1091555324/7588944049AEFEAD83D5890D4DE6AC5313A7C4B3C92DC37C1CA6DF5A24C056DC).

**Comment by umarmughal824** [comment]
> Screenshots look good. You can get a [PNG of the logo from InVision](https://projects.invisionapp.com/assets/21535972/1091555324/7588944049AEFEAD83D5890D4DE6AC5313A7C4B3C92DC37C1CA6DF5A24C056DC).

this is how it looks like now

Screenshot 2021-07-30 at 17 57 25

**Review by pdpinch — APPROVED** [review]
Screenshots are good!

**Review by asadiqbal08 — APPROVED** [review]
👍

**Pull request merged**
