### PR TITLE
Fixes to  Featured Carousel

### PR DESCRIPTION
**Pull request by JenniWhitman**
# What are the relevant tickets?
updates https://github.com/mitodl/hq/issues/2290

# Description (What does it do?)
Fixes sizing and behavior of carousel. Fixes background. Still some small tweaks, but we're pushing where we're at now so bilal can work with the skewed text

# Screenshots (if appropriate):
Screenshot from 2023-09-14 15-43-48
Screenshot from 2023-09-14 15-44-02
Screenshot from 2023-09-14 15-44-13

### CODE REVIEW

**Comment by JenniWhitman** [comment]
erm - ignore the video component changes if posssible - I merged that in to line things up and it's not merged into master yet

**Review by jkachel — APPROVED** [review]
I think this looks OK on desktop. On mobile, paging through the cards pages at the same rate as it does on the desktop, though:

Simulator Screen Recording - iPhone 14 Pro Max - 2023-09-15 at 08 34 27

(This is in iOS Simulator.) If this is something that can be fixed in a future PR to not hold up other work, though, let me know.

**Review by jkachel — CHANGES_REQUESTED** [review]
I clicked the wrong thing - meant to select request changes

**Comment by JenniWhitman** [comment]
> I think this looks OK on desktop. On mobile, paging through the cards pages at the same rate as it does on the desktop, though:
> (This is in iOS Simulator.) If this is something that can be fixed in a future PR to not hold up other work, though, let me know.

Yeah - going to have to fix a few things anyway (and possibly rework that component anyway), so I'm going with "ship it for now, because we're going to be doing updates shortly".

**Review by jkachel — APPROVED** [review]
Approving per slack convo

**Pull request merged**
