### PR TITLE
944 about page design tweaks

### PR DESCRIPTION
**Pull request by rachellougee**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [ ] Mobile width screenshots

#### What are the relevant tickets?
https://github.com/mitodl/mitxonline/issues/944

#### What's this PR do?
design tweaks requested in https://github.com/mitodl/mitxonline/issues/944

#### How should this be manually tested?
Go to frontend to see the style changes (Reference to css file attached to ticket)

#### Screenshots (if appropriate)
PRICE box, hero-block font size, and margin changes
image

course card border style change
image

course card hover
image

Removed hover on Instruction card (not actionable)
image

dashboard font size, badge, and button changes
image

Checkout 
image

dropdown menu
image

button hover 
image

hover on the course title
image

### CODE REVIEW

**Comment by rachellougee** [comment]
@pdpinch I've included the screenshots, please take a look when you get a moment. thanks

**Review by collinpreston — CHANGES_REQUESTED** [review]
Disregard my comment.  No clue what was going on.

**Comment by rachellougee** [comment]
@collinpreston This appears on RC as well, I don't see the style changes in css file. Could you let me know what expect to change?
image

**Review by collinpreston — APPROVED** [review]
Looks good!

**Review by pdpinch — APPROVED** [review]
All for the better!

**Pull request merged**
