### PR TITLE
Implement logged-ui in the site header

### LINKED ISSUE #22: Implement logged-in UI in the site header
Related: #21 

**Acceptance criteria:**
- When logged-in, the user's first name with a downward arrow are shown in the site header in non-mobile widths, and they match the designs
- Clicking the logged-in user's name or the arrow reveals a dropdown with working links that match the designs (with the exception of "Change password")
  - *NOTE:* For now, the look and feel of the dropdown can be the same for desktop and mobile views

**Not needed:**
- "Change password" link – Right now, this form is included in the Settings page. If we implement this as a separate page, that can be done in a separate issue
- "Help" link – This can be done in a separate issue
- Fixing the styling of the hamburger menu or overlay menu options in mobile view (https://github.com/mitodl/mitxonline/issues/23)

### PR DESCRIPTION
**Pull request by umarmughal824**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
fixes #22

#### What's this PR do?
(Required)

#### How should this be manually tested?
Implement logged-ui in the site header

#### Screenshots (if appropriate)
Screenshot 2021-08-05 at 17 50 24
Screenshot 2021-08-05 at 17 51 55
Screenshot 2021-08-05 at 17 52 23
Screenshot 2021-08-05 at 17 52 32
Screenshot 2021-08-05 at 17 52 41
Screenshot 2021-08-05 at 17 52 54
Screenshot 2021-08-05 at 17 53 05
Screenshot 2021-08-05 at 17 53 12

### CODE REVIEW

**Review by gsidebo — CHANGES_REQUESTED** [review]
A couple implementation details that need to be fixed:

1. The profile image icon should be removed so the "Profile" link appears just like the other options
    
    ss 2021-08-05 at 16 58 54
2. The "Profile" link should also appear in the mobile version of the menu. I don't think there's any good reason to have different options in the desktop vs. mobile menus. In terms of code, please try to implement the menu links once so we don't have to maintain 2 sets of the same links
    
    ss 2021-08-05 at 17 01 58

**Review by pdpinch — APPROVED** [review]
screenshots look good to me, other than the things Gavin already mentioned.

**Comment by umarmughal824** [comment]
> A couple implementation details that need to be fixed:
> 
> 1. The profile image icon should be removed so the "Profile" link appears just like the other options
>    ss 2021-08-05 at 16 58 54
> 2. The "Profile" link should also appear in the mobile version of the menu. I don't think there's any good reason to have different options in the desktop vs. mobile menus. In terms of code, please try to implement the menu links once so we don't have to maintain 2 sets of the same links
>    ss 2021-08-05 at 17 01 58

@gsidebo good point, but I could not see that profile item in the menu on my side. Let me rebase it to the updated main.

**Comment by umarmughal824** [comment]
@gsidebo we have two different menus here one is a dropdown (desktop version) and another one is a hamburger (mobile version) so that's why Arslan has kept it in the separate classes. So in order to convert it into one that would not be a quick solution and would require is time taking to adjust the design and rest so please create a separate issue for that.

**Comment by umarmughal824** [comment]
@pdpinch / @gsidebo This is how it looks like now

Screenshot 2021-08-06 at 15 55 33
Screenshot 2021-08-06 at 15 55 47

**Review by gsidebo — CHANGES_REQUESTED** [review]
I'm getting a situation where the overlay menu is not disappearing when I click one of the options in the mobile view menu. To reproduce:

1. Log in with the browser in mobile view
2. Open the menu and select settings or profile
3. Open the menu again after the new page loads and select settings or profile

The overlay stays on the screen

**Review by gsidebo — APPROVED** [review]
Looks great! 👍

**Pull request merged**
