### PR TITLE
add financial aid models to admin and load country income thresholds

### LINKED ISSUE #559: Ecommerce: add mangement command to load country income threshold data
#### Acceptance Criteria:
- [x] Management command to load country threshold data
- [x] Add this management command to `bin/post_compile` so it automatically updates on deployments

### PR DESCRIPTION
**Pull request by umarmughal824**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
fixes #559 

#### What's this PR do?
adds financial add models to admin and load country income thresholds

#### How should this be manually tested?
Just run the management command and that should load all the threshold incomes for each country
`docker-compose exec web python manage.py load_country_income_thresholds flexiblepricing/data/country_income_thresholds.csv`

#### Screenshots (if appropriate)
Screenshot 2022-05-17 at 18 02 03
Screenshot 2022-05-17 at 18 02 09

### CODE REVIEW

**Comment by jkachel** [comment]
Getting an error trying to run the management command using the supplied CSV file:

```
Traceback (most recent call last):
  File "/src/./manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/src/flexiblepricing/management/commands/load_country_income_thresholds.py", line 20, in handle
    import_country_income_thresholds(options["csv_path"])
  File "/src/flexiblepricing/api.py", line 50, in import_country_income_thresholds
    country_income_thresholds = parse_country_income_thresholds(csv_path)
  File "/src/flexiblepricing/api.py", line 37, in parse_country_income_thresholds
    income_thresholds = [
  File "/src/flexiblepricing/api.py", line 37, in <listcomp>
    income_thresholds = [
  File "/usr/local/lib/python3.9/csv.py", line 111, in __next__
    row = next(self.reader)
ValueError: I/O operation on closed file.
```

File definitely exists in the container and can be read.

**Comment by umarmughal824** [comment]
> Getting an error trying to run the management command using the supplied CSV file:
> 
> ```
> Traceback (most recent call last):
>   File "/src/./manage.py", line 19, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
>     output = self.handle(*args, **options)
>   File "/src/flexiblepricing/management/commands/load_country_income_thresholds.py", line 20, in handle
>     import_country_income_thresholds(options["csv_path"])
>   File "/src/flexiblepricing/api.py", line 50, in import_country_income_thresholds
>     country_income_thresholds = parse_country_income_thresholds(csv_path)
>   File "/src/flexiblepricing/api.py", line 37, in parse_country_income_thresholds
>     income_thresholds = [
>   File "/src/flexiblepricing/api.py", line 37, in <listcomp>
>     income_thresholds = [
>   File "/usr/local/lib/python3.9/csv.py", line 111, in __next__
>     row = next(self.reader)
> ValueError: I/O operation on closed file.
> ```
> 
> File definitely exists in the container and can be read.

Could you try once more by restarting your container? I did not get any such error even once.

**Comment by umarmughal824** [comment]
> I rebuilt and restarted the containers and am still seeing the error. Looking at it, the `income_thresholds` line (37) probably just needs an indent - it's outside the with so the file's closed at that point.

You could check that it's running till the end `ZW,0` in the attached screenshots. Re-ran still going till the end and line 37 is already in the with block and in the same scope

Screenshot 2022-05-18 at 12 38 30

Screenshot 2022-05-18 at 12 44 58

**Comment by umarmughal824** [comment]
@jkachel It's already in the with block and working fine as shown in the previous comment with the attached screenshots. But if I move that block out of with statement then it produces the error that you are asking for.

Maybe it's being moved out of with statement on your side. Could you please confirm it?

Screenshot 2022-05-18 at 17 43 23

Screenshot 2022-05-18 at 17 43 08

**Pull request merged**
