### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by rhysyngsun**
#### What are the relevant tickets?
N/A

#### What's this PR do?
This PR updates documentation and configures github actions to publish them.

#### How should this be manually tested?
You can run `./pants docs ::` locally, then load the generated `dist/sphinx/index.html` to see the documentation. That should match the documentation deployed to pages here: https://mitodl.github.io/mitxonline/

### CODE REVIEW

**Comment by jkachel** [comment]
pulled and built docs locally, looks identical to the deployed copy so seems good to me 👍

**Comment by pdpinch** [comment]
Does it make sense? 😁

**Comment by jkachel** [comment]
Ah - sorry, did not realize I needed to review content too. The docs make sense but there are a handful of formatting issues:
- In configuration/open_edx.rst - third-level nested list isn't rendering correctly
- In ecommerce/overview.rst - subheadings and additional paragraphs under Goals and Prior Art aren't rendering correctly
- In ecommerce/subsystems/reporting.rst - subheadings and additional paragraphs under Use Cases aren't rendering correctly

The only versioned data model described here is the Product Subsystem one, and that uses django-reversion; should the data model description for that be updated to remove the versioning table?

**Comment by rhysyngsun** [comment]
@jkachel addressed your feedback

**Comment by jkachel** [comment]
Changes look good. Found a handful more smallish things after another look and running through redeploying mitxonline:
- ecommerce/subsystems/product.rst - API endpoints are rendered on one line and lack formatting for the request (like on the Basket subsystem page)
- ecommerce/subsystems/basket.rst - API endpoints are rendered on one line
- configuration/open_edx.rst - link to devstack under Setup edX devstack renders incorrectly
- configuration/open_edx.rst - yaml snippet (under Configure MITx Online as a OAuth provider) has commas after some of the options
- configuration/open_edx.rst - Under Django Admin section, slug field should match "Backend name" (this tripped me up the first time around)

**Comment by rhysyngsun** [comment]
@jkachel addressed those too

**Comment by jkachel** [comment]
Sorry, one more thing - the second OAuth section (Configure Open edX to support OAuth2) in configuration/open_edx.rst also needs its list fixed. That should be it, though; the rest of it looks good.

**Review by jkachel — CHANGES_REQUESTED** [review]
see previous comment

**Pull request merged**
