### PR TITLE
4012: Improve screen reader accessibility of the site-wide banner.

### PR DESCRIPTION
**Pull request by collinpreston**
### What are the relevant tickets?
https://github.com/mitodl/hq/issues/4012

### Description (What does it do?)
Improves screen reader accessibility of the site-wide banner.

### How can this be tested?

1. Create a new banner at http://mitxonline.odl.local:8013/cms/snippets/cms/sitebanner/. Ensure that the banner has a hyperlink.
2. Visit http://mitxonline.odl.local:8013/
3. Using a screen reader, tab through the page.  Ensure that the hyperlink in the banner is read by the screen reader prior to the close button.
4. Ensure the banner is properly formatted on different screen sizes.

### CODE REVIEW

**Review by annagav — CHANGES_REQUESTED** [review]
When I tab through the page the link in the banner is not getting selected.

**Comment by collinpreston** [comment]
> When I tab through the page the link in the banner is not getting selected.

Can you share the content from CMS for your banner?

**Comment by annagav** [comment]
> > When I tab through the page the link in the banner is not getting selected.
> 
> Can you share the content from CMS for your banner?

<p data-block-key="u1wft">dfgnkj<a id="3" linktype="page">Home Page</a>efngksjfn her again</p>

**Review by annagav — APPROVED** [review]
The order of the banner content and the close link is read in order now.

**Pull request merged**
