### PR TITLE
Clarify enrollable run

### PR DESCRIPTION
**Pull request by annagav**
### What are the relevant tickets?
Related to https://github.com/mitodl/hq/issues/4543

### Description (What does it do?)
Find all places where we use the definition of an enrollable run.

### How can this be tested?
Nothing should break.

### CODE REVIEW

**Review by cp-at-mit — COMMENTED** [review]
Should https://github.com/mitodl/mitxonline/blob/0f7d16b453c28650c86bf73ea8903876c63248a7/courses/models.py#L749 also be updated?

**Review by cp-at-mit — COMMENTED** [review]
Calls to `_relevant_course_qset_filter` were replaced with `get_enrollable_courseruns_qs`.  `_relevant_course_qset_filter` included a `.exclude(enrollment_start=None)`.  Should `get_enrollable_courseruns_qs` also filter by `.exclude(enrollment_start=None)`?

**Comment by annagav** [comment]
There is a failing test for counting the querries for departments api. Not sure where I've added complexity. Looking into it.
`FAILED courses/views/v2/views_test.py::test_get_departments[15-100] - Failed: Expected to perform 23 queries or less but 33 were done`

**Comment by annagav** [comment]
> Calls to `_relevant_course_qset_filter` were replaced with `get_enrollable_courseruns_qs`. `_relevant_course_qset_filter` included a `.exclude(enrollment_start=None)`. Should `get_enrollable_courseruns_qs` also filter by `.exclude(enrollment_start=None)`?

So this statement ` Q(enrollment_start__lt=now)` should filter out both dates that are in the future and null values.

**Review by cp-at-mit — APPROVED** [review]

**Pull request merged**
