### PR TITLE
When creating enrollment set is_active explicitly in the enrollment api call

### PR DESCRIPTION
**Pull request by annagav**
### What are the relevant tickets?
Fix https://github.com/mitodl/mitxonline/issues/2225 and https://github.com/mitodl/mitxonline/issues/1797

### Description (What does it do?)
If use enrolls, unenrolls, and enrolls again, the course run enrollment in edx should be active, otherwise the user can't access the course on edx, just like it happened for this user https://github.com/mitodl/hq/issues/4367.

On open edx `is_active = False` is equivalent to being unenrolled.

### How can this be tested?
Locally you can test if by enrolling in a course for an audit track, then unenrolling, then paying again. You can pay with a coupon too.
The api would get called again. This double call of create enrollment api is going to set is_active to true on repeated call.

### CODE REVIEW

**Comment by pdpinch** [comment]
Why?

**Comment by annagav** [comment]
> Why?

If user re-enrolls their enrollment stays inactive and they can't access the course through the courseware.

**Review by cp-at-mit — APPROVED** [review]

**Comment by annagav** [comment]
So just adding here more clarification on the issue.

The enrollment stays inactive only following a "verified" enrollment as a result of payment for the course run.

If re-enroll in as audit again, then is works correctly.

**Comment by annagav** [comment]
So I have been playing with the api and what I found is this:
Set up: There is an existing enrollment that has `is_active=False`( meaning the user unenrolled).
Action: 
If I make an api ( `edx_client.enrollments.create_student_enrollment`)call with the same `MODE` is_active gets set to True.
If I make the same api call but the MODE is not the same (changing from `audit` to `verified` or vice versa), then the MODE gets updated but `is_active` stays False.

**Pull request merged**
