### PR TITLE
fix: accessibility fixes for Product Detail page and dashboard

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [ ] Mobile width screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
#171 

#### What's this PR do?
- Fixes the accessibility on the Product detail page
- Fixes accessibility on the Dashboard page

**Note for Reviewer:**
- Lighthouse complains about descending order of headings to be followed for accessibility e.g. `h1->h2->h3...` But in our case, we were using `h1` and then directly `h4` so i had to make our design use the heading tag in order and for that, i had to override the style of `h4` as `h2` in the specific classes to keep the design intact as well as resolve accessibility issues by LightHouse. I'm aware of using the common `h2` style but using `h2` here as is was a notable difference
- The second complaint was the color contrast so least possible color to fix the issue in tiles.

#### How should this be manually tested?
- Open the dashboard page and check the accessibility and design. There should be no accessibility errors for that specific page and there should be no notable design changes
- Verify the same as above on the Product detail page.

#### Screenshots (if appropriate)
**Tiles Before**
Screenshot 2021-09-17 at 1 32 56 PM

**Tiles After**
Screenshot 2021-09-17 at 1 33 05 PM

**Dashboard Before**
Screenshot 2021-09-17 at 1 35 43 PM

**Dashboard After**
Screenshot 2021-09-17 at 1 35 55 PM

**Faculty Before**
Screenshot 2021-09-17 at 1 37 54 PM

**Faculty After**
Screenshot 2021-09-17 at 1 38 07 PM

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@pdpinch, Can you please take a look at the screenshots and let me know what you think of the changes done in regard to achieving `100% Accessibility`. Also, I have posted reviewer details in the PR description about the approach:

>- Lighthouse complains about descending order of headings to be followed for accessibility e.g. h1->h2->h3... But in our case, we were using h1 and then directly h4 so i had to make our design use the heading tag in order and for that, i had to override the style of h4 as h2 in the specific classes to keep the design intact as well as resolve accessibility issues by LightHouse. I'm aware of using the common h2 style but using h2 here as is was a notable difference
>- The second complaint was the color contrast so least possible color to fix the issue in tiles.


Additionally, this PR is based on targeting 100% accessibility which I'm not sure if we can compromise or not e.g. 
- If we don't do the tile color change for contrast we get a `98%` accessibility result which is also good but is it acceptable?

**Comment by pdpinch** [comment]
Sorry, I'm not following the specifics. Which title is it that has a h4 style but needs to be an h2?

And which colors are failing the contrast test? 

If it's easier, you could give me a URL of the test page and I can run lighthouse in my browser.

**Comment by arslanashraf7** [comment]
@pdpinch ,

> Sorry, I'm not following the specifics. Which title is it that has a h4 style but needs to be an h2?

1.1 On the Product detail page the instructor name is h4

Screenshot 2021-09-15 at 3 28 03 AM

1.2 On the dashboard, the enrolled course name and `Enroll Now(In course of no enrollment)` are h4
Screenshot 2021-09-15 at 3 31 10 AM


> And which colors are failing the contrast test?

2.1 On product detail page, The tiles background color is failing the contrast test
Screenshot 2021-09-15 at 3 26 51 AM

2.2 On the product detail page, The instructor description color is failing the contrast test (You can see the screenshot in 1.2)


 
> If it's easier, you could give me a URL of the test page and I can run lighthouse in my browser.

- For Product details failing tests mentioned above you can use https://rc.mitxonline.mit.edu/courses/course-v1:MITx+14.100x/
- For dashboard failing tests, you can use https://rc.mitxonline.mit.edu/dashboard

**Comment by asadiqbal08** [comment]
@arslanashraf7 although, It improves the accessibility points but If I looked around our *.html templates then I figured it out we are not incorporating the `ARIA` semantics to most of our HTML DOM elements such as `<li>`, It would be just a suggestion if we take care of it.

But in our code base, I came to know that the **IDs used in ARIA and labels are not unique** as an example, under `/authentication/profile.html`, `/authentication/login.html` and `authentication/register.html` we defined the same ID for `<div>` elements. 
```
<div id="login-page">
```
same for 
```
<div id="header"></div>
```

**Review by asadiqbal08 — CHANGES_REQUESTED** [review]
Some concerns about ID uniqueness in HTML

**Comment by pdpinch** [comment]
I'm going to check with our accessibility expert about the heading order, but can I ask what happens if we make the instructor name an H3, and the course title on the dashboard an H2? If it's easier, you can tell me where I can see implementations of H2 and H3.

**Comment by arslanashraf7** [comment]
@pdpinch,

>can I ask what happens if we make the instructor name an H3, and the course title on the dashboard an H2?

Their font size reasonably changes w.r.t to the design.

>If it's easier, you can tell me where I can see implementations of H2 and H3.

Sure you can see the common styling of all the headings in [common.scss](https://github.com/mitodl/mitxonline/blob/main/static/scss/common.scss). To be specific you can see the styling of H2 [here](https://github.com/mitodl/mitxonline/blob/main/static/scss/common.scss#L18) and H3 [here](https://github.com/mitodl/mitxonline/blob/main/static/scss/common.scss#L25).

Let me know if this wasn't what you were asking.

**Comment by pdpinch** [comment]
Thanks for the details! 

1.1 Please make the instructor's name into an H3
1.2. Please make the course title into an H2

I'm still getting some design guidance on the colors.

**Comment by arslanashraf7** [comment]
@asadiqbal08 Thanks for raising the concerns, I'm responding to them below probably you can let me know if you agree.

> @arslanashraf7 although, It improves the accessibility points but If I looked around our *.html templates then I figured it out we are not incorporating the `ARIA` semantics to most of our HTML DOM elements such as `<li>`, It would be just a suggestion if we take care of it.

The scope of adding the ARIA IDs in all the HTML elements is very large, What is your opinion shouldn't we do that in another singular ticket, in addition, Lighthouse doesn't currently restrain about all the needing to have ARIA attr. I'd look for your response before proceeding on this.

> But in our code base, I came to know that the **IDs used in ARIA and DOM elements are not unique** as an example, under `/authentication/profile.html`, `/authentication/login.html` and `authentication/register.html` we defined the same ID for `<div>` elements.
> 
> ```
> <div id="login-page">
> ```

This might not be an issue considering we only need unique Ids within a single HTML file unless some other file is getting included. So as long as we don't duplicate the Ids within a single file there should be no issue. Let me know what you think?

> 
> ```
> <div id="header"></div>
> ```

Your concerns regarding header should have been fixed in https://github.com/mitodl/mitxonline/pull/168.

**Comment by arslanashraf7** [comment]
> Thanks for the details!
> 
> 1.1 Please make the instructor's name into an H3
> 1.2. Please make the course title into an H2
> 
> I'm still getting some design guidance on the colors.

@pdpinch The mentioned changes have been incorporated and the design screenshots for your reference have been updated in the PR description as well.

**Comment by pdpinch** [comment]
InVision has been updated with higher-contrast colors: https://projects.invisionapp.com/share/KH11D3ZN53GC/#/screens/455477372/comments/145302163 

> 2.1 On product detail page, The tiles background color is failing the contrast test

Change the background to `#465A5B`

2.2 On the product detail page, The instructor description color is failing the contrast test (You can see the screenshot in 1.2)

Change the text color to `#666666`

**Comment by asadiqbal08** [comment]
> This might not be an issue considering we only need unique Ids within a single HTML file unless some other file is getting included. So as long as we don't duplicate the Ids within a single file there should be no issue. Let me know what you think?


@arslanashraf7, On my local setup, Lighthouse was complaining about the uniqueness of ID for DOM elements, 
`ARIA ids are not unique`, It seems me some of the HTML DOM elements having the same ID so I mentioned it.

and just as a good practice, ID elements should be unique regardless of page rendering. I have `register.html` and the block under it containing a `<div id="login-page">`.

If you think, it can increase the effort then I am ok to do separately.

**Review by asadiqbal08 — APPROVED** [review]
Ok, I took the pull that contains the header changes and re run the lighthouse, it is not throwing ID uniqueness error in report but as a suggestion, 
- In improving user's accessibility, we should try look around those DOM elements where we can use the ARIA semantics.
- Regarding the ID, It should also be fixed separately because it does not make sense to have a ID as `login-page` on the `registration.html` template.

**Comment by arslanashraf7** [comment]
> @arslanashraf7, On my local setup, Lighthouse was complaining about the uniqueness of ID for DOM elements,
> `ARIA ids are not unique`, It seems me some of the HTML DOM elements having the same ID so I mentioned it.

As mentioned earlier, this complaint is resolved after merging [header accessibility PR](https://github.com/mitodl/mitxonline/pull/168)

> and just as a good practice, ID elements should be unique regardless of page rendering. I have `register.html` and the block under it containing a `<div id="login-page">`.

I've updated the page Ids in register and profile to be unique.

**Comment by arslanashraf7** [comment]
@pdpinch The screenshots in the PR description now represent the latest changes as per this PR. Let me know if they look good to you.

**Comment by arslanashraf7** [comment]
> InVision has been updated with higher-contrast colors: https://projects.invisionapp.com/share/KH11D3ZN53GC/#/screens/455477372/comments/145302163
> 
> > 2.1 On product detail page, The tiles background color is failing the contrast test
> 
> Change the background to `#465A5B`
> 
> 2.2 On the product detail page, The instructor description color is failing the contrast test (You can see the screenshot in 1.2)
> 
> Change the text color to `#666666`


@pdpinch Thank you for taking it on with the designers and finalizing the changes. The screenshots in the PR description now represent the latest changes as per all the above-suggested changes for `headings order & contrast`. Let me know if they look good to you.

**Comment by arslanashraf7** [comment]
@pdpinch, Should i go ahead and merge this PR?

**Comment by pdpinch** [comment]
Yes please

**Pull request merged**
