### PR TITLE
New MITxOnline Logo

### PR DESCRIPTION
**Pull request by annagav**
### What are the relevant tickets?
Fix https://github.com/mitodl/hq/issues/3337

### Description (What does it do?)
Updating mitx online logo in homepage, footer, program record, certificates, receipt page.

### Screenshots (if appropriate):
Screenshot 2024-01-26 at 1 41 40 PM
Screenshot 2024-01-26 at 1 47 34 PM
Screenshot 2024-01-26 at 2 38 27 PM
Screenshot 2024-02-01 at 9 20 48 AM

Screenshot 2024-02-01 at 9 23 10 AM
Screenshot 2024-02-01 at 9 47 34 AM

### CODE REVIEW

**Comment by annagav** [comment]
@mbilalmughal Could you take clarify what the records page should look like. The screen shot in the description.

**Comment by annagav** [comment]
Updated screenshot:
Screenshot 2024-01-29 at 9 27 32 AM

**Comment by pdpinch** [comment]
@annagav, the header is looking good, but you've got the wrong logo for the footer. We should be using the [MIT Open Learning logo](https://www.dropbox.com/scl/fo/3vjt253bq0wnvcwqazc6r/h?rlkey=n2ouxauz1g1nrnd0ai1adi7t6&dl=0) in the footer. 

@mbilalmughal can you take a look at these screenshots too?

**Comment by mbilalmughal** [comment]
@annagav For the footer, we are using the Open Learning logo. Please see the attached image.

- [Figma Link for MITx Online Logo](https://www.figma.com/proto/GFl0GZREDaWmdRytsNiET2/MIT-Logo-Header-%2F-Footer?page-id=0%3A1&node-id=1-2&mode=design&t=Pr4QnkU9vloln5j7-1)
- the width will be 129px 
logo-footer


Regarding the product card, I am currently working on the [missing pages of MITx Online,](https://github.com/mitodl/hq/issues/3413) and this page is already underway.

**Comment by mbilalmughal** [comment]
@annagav Thanks ana for updating the logo, Now LGTM 👍

**Review by collinpreston — APPROVED** [review]
One failing test - maybe unrelated? Looks good otherwise.

**Review by pdpinch — APPROVED** [review]

**Review by pdpinch — APPROVED** [review]
lgtm

**Pull request merged**
