### PR TITLE
Updates button styling to sync border widths; updates close button on drawer

### LINKED ISSUE #1291: Program Dashboard: Close button is too small
1. Compare this screen shot:

Screen Shot 2022-12-14 at 11 09 49 AM

2. To the design at https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468431707/preview?scrollOffset=245

### acceptance criteria

- [ ] close button should never overlap with course title, at any window width
- [ ] the button needs to be large enough to click or tap, even at mobile widths
- [ ] While we're at it, clicking or tapping outside of the drawer should close it.

### LINKED ISSUE #1292: Enroll button resizes on mouseover
### Steps to Reproduce

1. visit https://rc.mitxonline.mit.edu/dashboard/?enable_programs#program_enrollment_drawer
2. open program drawer
3. mouse over the 'Enroll' button on any course

### Actual Behavior

Enroll button resizes on mouseover

### Screenshot or Screencast

https://user-images.githubusercontent.com/430126/208182202-92c9d998-e210-4cf2-a2ab-49f5b578e1eb.mp4

### PR DESCRIPTION
**Pull request by jkachel**
#### Pre-Flight checklist

- [X] Screenshots and design review for any changes that affect layout or styling
  - [X] Desktop screenshots
  - [X] Mobile width screenshots
- [X] Testing
  - [X] Code is tested
  - [X] Changes have been manually tested

#### What are the relevant tickets?

Closes #1292 
Closes #1291 

#### What's this PR do?

Updates the styling on the Enroll Now button so the border width doesn't change when you hover into and out of the button.
Updates the close widget to be more like the design.

#### How should this be manually tested?

Hovering into and out of the Enroll Now button in the Program Drawer should no longer cause the UI to move about. 
The close button should be a larger thin X now instead of the `&times;` glyph, and the program title should no longer run into it if the title is sufficiently long.

#### Screenshots (if appropriate)

CleanShot 2022-12-19 at 11 45 46 2
Screen Shot 2022-12-19 at 11 45 21 AM
image

### CODE REVIEW

**Review by arslanashraf7 — COMMENTED** [review]
The enroll button style works great now.


I have a couple of things to mention though:

1. The close button still has the tendency to overlap the title on specific widths.
    E.g. See the screenshot below:
    image

2. I noticed an issue (Not related to this PR though), So we redirect the user to the Course Details page upon clicking `Enroll` button, But the behavior might be inconsistent when there is no `Course details` link for a course. In this case, the dashboard page reloads itself, This behavior can be noticed at https://rc.mitxonline.mit.edu/dashboard/?enable_programs#program_enrollment_drawer. (Try clicking `Enroll` button on any course that doesn't have `Course details` link in it).


Maybe for point#2 we shouldn't show `Enroll` button when there is no `Course details` link for it to go to. A related comment is https://github.com/mitodl/mitxonline/pull/1297#pullrequestreview-1224032140

@jkachel FYI, @pdpinch

**Comment by jkachel** [comment]
Updated the drawer title to use margin (and slightly more of it) in https://github.com/mitodl/mitxonline/pull/1296/commits/a4ee9bab579b23cea9135e154a36482d5b87393f; that seems to fix the collision issue:
CleanShot 2022-12-20 at 10 24 39

Regarding the enroll button: I will take care of that in #1297 - disabling the enroll button if there's no course page makes sense (in testing, clicking that resulted in no enrollment at all and a redirect to the dashboard) but there's changes in that PR that will facilitate the change, so better it goes there.

**Review by arslanashraf7 — APPROVED** [review]
Looks great 👍

**Review by rachellougee — APPROVED** [review]
Enroll button and close icon look good to me.

**Pull request merged**
