### PR TITLE
add/enable GTM support

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
#73 

#### What's this PR do?
- Adds the missing pieces from the support of GTM
- Removed the duplicate HTML for partials
- Generally, Ports the context processor from the xPRO to pass the GTM/GA config values to the Django templates
**Note:**

I didn't port `GTM` related configuration/code for the checkout/payment part since it's not yet part of MITxOnline.

#### How should this be manually tested?
- This is basically just that addition of the boilerplate code, but to test it you'll have to create accounts on https://tagmanager.google.com and https://analytics.google.com/analytics/web/?authuser=5#/a206499573w284900088p250338982/admin/property/settings.
- Once the accounts are created you will need to set two configuration values `GTM_TRACKING_ID` and `GA_TRACKING_ID` which you will find after creating a project on the GTM console mentioned above and the analytics admin property creation relatively.

#### Where should the reviewer start?
Probably, after setting the configuration values when you visit different pages on the website you should see similar Requests (https://www.googletagmanager.com/gtm.js?id=XXXXX),  https://www.google-analytics.com/j/collect?....

#### Some Screenshots from the Google Consoles:

Screenshot 2021-09-03 at 3 48 00 PM
Screenshot 2021-09-03 at 10 41 01 AM
Screenshot 2021-09-03 at 10 41 12 AM
Screenshot 2021-09-03 at 10 41 19 AM
Screenshot 2021-09-03 at 10 41 35 AM
Screenshot 2021-09-03 at 10 41 44 AM

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@pdpinch You can take a look at the screenshots that I've added from my own test account's Analytics/GTM board as I didn't have MIT's test account if there was one. These are from the basic site events for visiting the pages.

Based on the above, I've added `Ready for Review` tag, let me know if you'd thought otherwise.

**Comment by arslanashraf7** [comment]
For anyone reviewing this, If you'd like to test, you can ask me for the relevant GTM/GA keys and console access if needed.

**Comment by asadiqbal08** [comment]
LGTM 👍 , 

Not related to this PR perhaps but I noticed one thing, we have defined `gtm_tracking_id` and `ga_tracking_id` in `AppContextSerializer` but we do not have any endpoint or usability in this project. maybe in the later requirements.

```
class AppContextSerializer(serializers.Serializer):
    """Serializer for the application context"""

    public_path = serializers.SerializerMethodField()
    gtm_tracking_id = serializers.SerializerMethodField()
    ga_tracking_id = serializers.SerializerMethodField()

```

**Review by asadiqbal08 — APPROVED** [review]

**Comment by arslanashraf7** [comment]
> LGTM 👍 ,
> 
> Not related to this PR perhaps but I noticed one thing, we have defined `gtm_tracking_id` and `ga_tracking_id` in `AppContextSerializer` but we do not have any endpoint or usability for this in this project. maybe in the later requirements.
> 
> ```
> class AppContextSerializer(serializers.Serializer):
>     """Serializer for the application context"""
> 
>     public_path = serializers.SerializerMethodField()
>     gtm_tracking_id = serializers.SerializerMethodField()
>     ga_tracking_id = serializers.SerializerMethodField()
> ```

Good point, we don't have an API endpoint to get and use the configurations so the serializer is not used. I believe we can remove it since it's unused, what are your thoughts @asadiqbal08 ?

**Comment by asadiqbal08** [comment]
Actually, I am not sure about the actual reason for introducing this Serializer in code base. mean the relevant ticket and purpose.

**Comment by arslanashraf7** [comment]
> Actually, I am not sure about the actual reason for introducing this Serializer in code base. mean the relevant ticket and purpose.

Okay, I'll go ahead with the merge after the rebase.

**Pull request merged**
