### PR TITLE
fix video on course page is not screen reader accessible

### LINKED ISSUE #512: Bug: Video on course page is not screen reader accessible
### Steps to Reproduce

- Try to access the video with a screen reader

### Expected Behavior

- The user should be able use the video player with the screen reader and be able to identify all the buttons.
- Note the the video player on the [xPRO product pages](https://xpro.mit.edu/programs/program-v1:xPRO+SysEngx/) works fine. 

### Actual Behavior

- Nope. Details below from our testers

---

### Details from testing

In the process of adding captions to this player, screen reader access was broken. 

Take this one https://mitxonline.mit.edu/courses/course-v1:MITxT+14.100x/ 

The ARC Toolkit shows the player has an invalid ARIA-LABEL of "YouTube Video Player".
image

I noticed this, sent it to @rjc for testing, and Rich shared this: "I have no idea if this is a YouTube embedded player, or something created by mitX or another third party. The mitX video on this page somehow disables all screen reader navigation within the player region after the play button is pressed. It also throws focus out of the region when you first click the play button, so in order to control the player you must:

- find the region in the document while the audio is playing (not always easy since audio covers up screen reader speech)
- tab into the player region since all screen reader navigation within the region is turned off (in fact, all content within the region seems to be hidden)
- tab till you find the pause button and press spacebar
- Once this is done, you can tab around inside the player region and you can use YouTube shortcuts like "k" to play/pause and arrows to move around.

There are buttons which are not labeled correctly; I think they are "full screen" and "mute". The are announced as "button" when they gain focus, and when they lose focus, they are announced correctly.  Basically, they have aria-live on these buttons for no reason I can understand; removing that and making sure that text within the button is visible, or using aria-label="text of label" on the button will suffice.

Again, I cannot figure out why the contents of the player region cannot be normally navigated. Is HTML being injected into an embedded YouTube player?   

For reference, here is a typical YouTube embed for a random mitX video:

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/YLf3eX-VkzQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
```

If you put this into a document, all controls show up via screen reader and navigation is fairly straightforward. YouTube has it's querks, but they are well understood by screen reader users at this point."

---

### Related Issues

https://github.com/mitodl/mitxonline/pull/491

### PR DESCRIPTION
**Pull request by umarmughal824**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [ ] Mobile width screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
fixes 

#### What's this PR do?
fixes #512

#### How should this be manually tested?
fix video on the course page is not screen-reader accessible

#### Screenshots (if appropriate)
Screenshot 2022-04-18 at 16 34 11
Screenshot 2022-04-18 at 16 34 29
Screenshot 2022-04-18 at 16 34 56
Screenshot 2022-04-18 at 16 35 29
Screenshot 2022-04-18 at 16 35 32
Screenshot 2022-04-18 at 16 35 44
Screenshot 2022-04-18 at 16 47 47
Screenshot 2022-04-18 at 16 47 54
Screenshot 2022-04-18 at 16 54 45
Screenshot 2022-04-18 at 16 54 49
Screenshot 2022-04-18 at 16 55 09
Screenshot 2022-04-18 at 16 55 11
Screenshot 2022-04-18 at 16 55 19
Screenshot 2022-04-18 at 16 55 27

### CODE REVIEW

**Comment by umarmughal824** [comment]
@arslanashraf7 In my opinion, it would be better to get @briangrossman's review first.

**Comment by briangrossman** [comment]
@umarmughal824 

From what I can tell in the screenshots, these look good. That being said, there a couple that didn't look quite right:


Audio button is selected, but it's saying: 'application, Markup, button'


Pause is selected, but it's saying: 'application, Markup, button'


Looks like Pause is selected, but it says Mute:



I'm ok with beginning a review at this point.

**Comment by umarmughal824** [comment]
> 
@briangrossman I don't use voice over much but as far as I have used I could tell from my experience is

- It's showing play button is selected but I have moved to the next through the tabs that's why it looks confusing.
- whenever we are any part of the page let's suppose a button, the screen reader read it like `Play (k) button` at `application, Markup, button` so it's telling the type of HTML element

In my opinion, that's the right behavior. Let's get it tested by the accessibility team after deployment they will tell us the exact behavior.

**Comment by arslanashraf7** [comment]
> @umarmughal824
> 
> That sounds like a good plan. Once you get the code reviewed, we'll share this with the accessibility testers. Thanks!

Thanks, I will review it now.

**Review by arslanashraf7 — APPROVED** [review]
👍 Looks good. 

I also looked at some recent [screen reader changes in video.js](https://github.com/videojs/video.js/pulls?q=is%3Apr+screen+reader+is%3Aclosed) and there are a few that look promising.
Though, there is an error on the console which I'm adding below which doesn't directly hurt anything visible though but I'll let @umarmughal824 decide on that.
Screenshot 2022-04-25 at 1 39 52 PM

**Comment by umarmughal824** [comment]
> 👍 Looks good.
> 
> I also looked at some recent [screen reader changes in video.js](https://github.com/videojs/video.js/pulls?q=is%3Apr+screen+reader+is%3Aclosed) and there are a few that look promising.
> 
> Though, there is an error on the console which I'm adding below which doesn't directly hurt anything visible though but I'll let @umarmughal824 decide on that. Screenshot 2022-04-25 at 1 39 52 PM

@arslanashraf7 as long as it's functional, we can proceed with that. Anyway, I will take a look on it myself

**Comment by umarmughal824** [comment]
@arslanashraf7 I have tried different versions of it and all of them are showing that error in the console. Even we have that error on RC as well but it's only happening on a few videos. 

Screenshot 2022-04-26 at 13 15 14

**Pull request merged**
