### PR TITLE
Upgrade to django 3.2

### LINKED ISSUE #101: Upgrade to django 3.2
As an engineer, I'd like to be using the same version of django as edx-platform. 

edx-platform is making a large effort to upgrade to django 3.2 before October. Although not required, it would be good for us to be on the same version, including related libraries. 

#### Acceptance Criteria:

- [x] test django 3.2 upgrade
- [x] review any deprecation warnings for related libraries
- [x] ~~research upgrading django-hijack which doesn't currently support django 3.2~~

### PR DESCRIPTION
**Pull request by umarmughal824**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
fixes #101 

#### What's this PR do?
Upgrade to django 3.2

#### How should this be manually tested?
Just check that everything is still functional and up

### CODE REVIEW

**Review by arslanashraf7 — CHANGES_REQUESTED** [review]
I was able to get my eyes on a warning regarding the default auto field for our models which came from Django 3.2 migration.

Although it's a warning, I think we should fix it by defining `DEFAULT_AUTO_FIELD` in our settings to resolve the it. Attaching the reference below:

Screenshot 2021-09-22 at 4 13 47 PM

**Comment by umarmughal824** [comment]
> I was able to get my eyes on a warning regarding the default auto field for our models which came from Django 3.2 migration.
> 
> Although it's a warning, I think we should fix it by defining `DEFAULT_AUTO_FIELD` in our settings to resolve the it. Attaching the reference below:
> 
> Screenshot 2021-09-22 at 4 13 47 PM

@arslanashraf7 thank's for pointing it out. It didn't go through my eyes that's why got skipped.

**Comment by umarmughal824** [comment]
The build is failing because of missing migrations in `robots` and `social_django` for which I have create a couple of open source PR's
https://github.com/python-social-auth/social-app-django/pull/354
https://github.com/jazzband/django-robots/pull/112

**Comment by umarmughal824** [comment]
@arslanashraf7 that's ready for review again.

**Review by arslanashraf7 — APPROVED** [review]
👍 Looks good.

**Pull request merged**
