### PR TITLE
Home Page Contact Component

### PR DESCRIPTION
**Pull request by JenniWhitman**
# What are the relevant tickets?
updates https://github.com/mitodl/hq/issues/1677
closes https://github.com/mitodl/hq/issues/2166

# Description (What does it do?)
Adds the hubspot form and social links to the bottom of the home page.

# Screenshots (if appropriate):
Screenshot from 2023-09-05 11-17-22
Screenshot from 2023-09-05 10-34-34

# How can this be tested?
Load everything, get the values for HUBSPOT_HOME_PAGE_FORM_GUID and HUBSPOT_PORTAL_ID from the linked [issue](https://github.com/mitodl/hq/issues/2166).
rebuild your container and load the home page - you should see the contact component. Test it at different widths and test that you can submit the form and that the resulting text is looking ok
Figma attached to check styling

# Additional Context
[Figma](https://www.figma.com/file/Gs4zIhOFv5gVvafawwl6PF/MITx-Online?node-id=929%3A5249&mode=dev)

### CODE REVIEW

**Review by collinpreston — CHANGES_REQUESTED** [review]
For me, the submit button is being cut off by the footer:
Screenshot 2023-09-05 at 15 18 46

Desktop, Chrome.

**Comment by JenniWhitman** [comment]
> For me, the submit button is being cut off by the footer: Screenshot 2023-09-05 at 15 18 46
> 
> Desktop, Chrome.

Odd. What width? I'll look. I might have moved the form up and down again and not checked, but pretty sure I haven't seen that in chromium.

**Review by collinpreston — APPROVED** [review]
Looks good to me.  The only thing that might need adjustment is the name or description of the field in order to better support screen readers.  Right now, the field label is just "email" and is not associated with the text above it that better explains that the email field is for subscribing to email updates.  I think this would need to be configured in HubSpot, if it's possible.

**Comment by JenniWhitman** [comment]
> Looks good to me. The only thing that might need adjustment is the name or description of the field in order to better support screen readers. Right now, the field label is just "email" and is not associated with the text above it that better explains that the email field is for subscribing to email updates. I think this would need to be configured in HubSpot, if it's possible.

I can put a task to look into this with the one for updating the prod form to match the sandbox one! Thank you - good point!

**Comment by JenniWhitman** [comment]
Created https://github.com/mitodl/hq/issues/2316

**Pull request merged**
