### PR TITLE
Updates to ancillary pages

### PR DESCRIPTION
**Pull request by jkachel**
### What are the relevant tickets?

Closes https://github.com/mitodl/hq/issues/3413

### Description (What does it do?)

A bunch of pages in MITx Online needed some updates to be in-line with the redesign work for the course pages, catalog, and front page. This adds those based on the styling provided by Bilal in https://www.figma.com/file/Gs4zIhOFv5gVvafawwl6PF/MITx-Online?node-id=4450%3A6795&mode=dev .

### Screenshots (if appropriate):

Sign in/create account:

Screenshot 2024-03-04 at 2 06 59 PM
Screenshot 2024-03-04 at 2 07 10 PM
Screenshot 2024-03-04 at 2 10 00 PM
Screenshot 2024-03-04 at 2 10 23 PM
Screenshot 2024-03-04 at 2 10 50 PM

Reset password:
image
image
image

Dashboard:
Screenshot 2024-03-04 at 2 11 25 PM
Screenshot 2024-03-04 at 2 05 59 PM

Order history:
Screenshot 2024-03-04 at 2 06 48 PM

Financial assistance:
Screenshot 2024-03-04 at 2 06 12 PM
Screenshot 2024-03-04 at 2 06 24 PM

Profile:
image

Screenshot 2024-03-04 at 2 05 47 PM

Program record:
Screenshot 2024-03-04 at 2 05 25 PM

Cart:
image

### How can this be tested?

Check the pages against the design.

Also, note:
* The blue page header banner should appear when the learner is logged in. (So, on the login/forgot password workflows, there should _not_ be a banner.) 
   * I'm not sure how this applies to the learner record.
* Some of the figures will be compensated a bit to accomodate the fact that Figma doesn't appear to accommodate descenders in margins and padding. (i.e. if the design lists 20px bottom margin, that 20px also includes the tails on "g j y", etc. but the browser does _not_ - the descenders are above the margin.) 

There are no functionality updates here - this should all be design work.

### CODE REVIEW

**Review by collinpreston — CHANGES_REQUESTED** [review]
Some of these issues, like the accessibility stuff, might be better suited to be resolved in follow up issues.

1. Should the catalog button (in the top header) be displayed on the login page?  The mock-ups don't show it, but I don't think it causes any harm being there.  I don't see any mock-ups with the catalog button included in the header.
2. Hovering over the "Continue" button on the login makes the button color white, and the text remains white, leading to the text not being visible.  The mock-ups show that the button should transition to a blue color.
3. The email field on the sign in page should transition to having a dark boarder when the field is hovered over.
4. The "Sign in" button in the top header should transition to having a blue color and white text when hovered over.
5. I would confirm if this behavior is expected, but the mock-ups show the Sign in "card" floating above the header when you scroll down on the page.
6. The Honor Code, Terms of Service, and Privacy Policy links on the Create Account should have red text and no underline when hovered over.
7. The background (light blue) on the catalog page does not extend to the top of the footer.
8. When not enrolled in any course and viewing the dashboard, the "browse our courses" link does not transition to red text when hovering. https://www.figma.com/proto/Gs4zIhOFv5gVvafawwl6PF/MITx-Online?type=design&node-id=4402-1559&t=JPk1dNrlM7YaN6px-0&scaling=min-zoom&page-id=4399%3A3891
9. Should clicking the "browse our courses" link on the dashboard page, when not enrolled in any courses, redirect you to the main MITx Online page or the catalog page?  Currently, it redirects to the main MITx Online page.  The mock-ups show appear to indicate it should redirect to the main page as well, but I would've imagined it would redirect to the catalog page.
10. Hovering on the "Explore Courses" button on the home page should transition the button color to blue.
11. Hovering on the "View MITx Online Catalog" should transition the button color to blue and text color to white.
12. Should the course cards listed on the MITx Online home page be darker when not hovered on?
13. The "apply" and "Place order" buttons on the checkout page should transition the button color to blue and text color to white.
14. The "course details" link on the checkout page should have red text and no underline when hovered over.
15. The background color of the checkout page should be blue.
16. The "Help & FAQs" link on the checkout page should have red text and no underline when hovered over.
17. The "Terms of service" and "Privacy policy" links on the checkout page should have red text and no underline when hovered over.
18. The text "Starts" on the course card on the checkout page should be bold.
19. The background color of the profile page should be blue.
20. Hovering over the Submit button on the profile page should transition the button's color to blue and text to white.
21. Last name, Country, and Year of Birth fields on the profile page should not announce "star" when being read by a screen reader.  We just need to ensure that the field are announced as required.
22. Email, new password, and old password fields on the account page should not announce "star" when being read by a screen reader.  We just need to ensure that the field are announced as required.
23. When focus is on the confirm password field of the account page, screen readers should read the label of the field.
24. The "What's the certifications track?" link on the course about page should not be red.
25. the "Payment deadline" text color on the course about page does not appear to be the same color as the mock-ups.
26. The "Instructor-paced" text and background should be updated to match the mock-ups.
27. When a course is associated with a program, the text indicating which program the course belongs to on the course about page should not be red.
28. When enrolled into a course with multiple enrollment dates, the course about page should display "July 15, 2023 - Enrolled" in green text rather than "Starts July 15, 2023 - Enrolled" or "Started July 15, 2023 - Enrolled".
29. When a course is associated with a program, the text on the course about page "Part of the following program" should not be bold.
30. Screen readers are not properly reading error messages for the email field on the sign in page.

**Comment by jkachel** [comment]
Quick notes on some of these while I work through the rest:

> 1. Should the catalog button (in the top header) be displayed on the login page? The mock-ups don't show it, but I don't think it causes any harm being there. I don't see any mock-ups with the catalog button included in the header.

The top bar is out of scope for this, I think; I agree that it doesn't cause harm there and I think it's also better to have it be consistent across the app. (Also some of the pages in the Figma are logged-in only and still use the logged-out header.)

> 8. Should clicking the "browse our courses" link on the dashboard page, when not enrolled in any courses, redirect you to the main MITx Online page or the catalog page? Currently, it redirects to the main MITx Online page. The mock-ups show appear to indicate it should redirect to the main page as well, but I would've imagined it would redirect to the catalog page.

This is as it was. (I think redirecting to catalog makes sense but this PR is just focusing on design changes.)

> 12. Should the course cards listed on the MITx Online home page be darker when not hovered on?

They don't appear to on RC or production, so assuming no here. (Same on the catalog page - we only have the dimming stuff on the product pages for programs.)

> 15. The background color of the checkout page should be blue.

I don't understand this one.. looking at the Figma design, it's `#F0F5F7`, which matches the other pages?

**Comment by jkachel** [comment]
More notes:

> 5. I would confirm if this behavior is expected, but the mock-ups show the Sign in "card" floating above the header when you scroll down on the page.

This really looks like a Figma thing but @mbilalmughal can you confirm this? We don't have a sticky top nav in the other parts of the site. 

> 7. The background (light blue) on the catalog page does not extend to the top of the footer.

More a note for me but this change is very, very subtle (at least on my screens) - I had to use a loupe via xScope to "see" the change. This wouldn't be a change that I made as part of this PR, though (it's the same way on RC), so maybe we can do this in a separate PR so this one doesn't get too much bigger.

> 19. The background color of the profile page should be blue.

Similar to 15, I don't quite understand this one either. (Thoughts, though: I see #eff3f6 on some places but the Figma lists specifically #f0f5f7 as the background for this.. but the loupe gives me #eff3f6 so I dunno.)

> 24. The "What's the certifications track?" link on the course about page should not be red.
> 25. the "Payment deadline" text color on the course about page does not appear to be the same color as the mock-ups.
> 26. The "Instructor-paced" text and background should be updated to match the mock-ups.
> 27. When a course is associated with a program, the text indicating which program the course belongs to on the course about page should not be red.

Not real sure about these since these are changes on pages that aren't in the mockup. @mb can you confirm these changes are supposed to be global? (If they are, does that need to apply to buttons too? The transition on some of these are different, even now - the Enroll Now buttons on the course about pages transition to white and the Create Account transitions to black, for instance.)

> 28. When enrolled into a course with multiple enrollment dates, the course about page should display "July 15, 2023 - Enrolled" in green text rather than "Starts July 15, 2023 - Enrolled" or "Started July 15, 2023 - Enrolled".
> 29. When a course is associated with a program, the text on the course about page "Part of the following program" should not be bold.

Where are these? The only mockups that are part of this PR in the Figma design are under "Missing Pages" - if these are updated elsewhere then we can take care of them in a separate issue.

**Comment by collinpreston** [comment]
@jkachel looks like 28 & 29 are shown mockups that are not under "missing pages" in figma.  I think for those 2 bullets, along with any other that you deem outside the scope of this issue, we create a new issue and specify them there.  I can help write that issue if you would like.

**Comment by collinpreston** [comment]
Regarding the blue background color comments: On the checkout page in figma, the background color of the page appears to be F0F5F7.  When I load the checkout page using this branch, I see the background color of f5f5f5.

**Comment by jkachel** [comment]
Changes made in https://github.com/mitodl/mitxonline/pull/2119/commits/9052fd8370cc9ec5dbaf2a675a79ea891abd0272 include:

- Reworks the Order Summary card so that it uses the new card format
- Fixes the hover and active styling on form elements within the card
- Fixes link text color within the card (black normally and red on hover)
- Refactors labels to be its own React component; this includes some styling changes to make the required marker's `aria-hidden` set to true and should clean up some readability issues for screen readers (tested with VoiceOver)
- Fixes styling of the no enrollments message on the Dashboard

There's some things in here that I'm waiting on feedback from @mbilalmughal so there will be some more changes later.

**Comment by mbilalmughal** [comment]
> More notes:
> 
> > 5. I would confirm if this behavior is expected, but the mock-ups show the Sign in "card" floating above the header when you scroll down on the page.
> 
> This really looks like a Figma thing but @mbilalmughal can you confirm this? We don't have a sticky top nav in the other parts of the site.
> 
> > 7. The background (light blue) on the catalog page does not extend to the top of the footer.
> 
> More a note for me but this change is very, very subtle (at least on my screens) - I had to use a loupe via xScope to "see" the change. This wouldn't be a change that I made as part of this PR, though (it's the same way on RC), so maybe we can do this in a separate PR so this one doesn't get too much bigger.
> 
> > 19. The background color of the profile page should be blue.
> 
> Similar to 15, I don't quite understand this one either. (Thoughts, though: I see #eff3f6 on some places but the Figma lists specifically #f0f5f7 as the background for this.. but the loupe gives me #eff3f6 so I dunno.)
> 
> > 24. The "What's the certifications track?" link on the course about page should not be red.
> > 25. the "Payment deadline" text color on the course about page does not appear to be the same color as the mock-ups.
> > 26. The "Instructor-paced" text and background should be updated to match the mock-ups.
> > 27. When a course is associated with a program, the text indicating which program the course belongs to on the course about page should not be red.
> 
> Not real sure about these since these are changes on pages that aren't in the mockup. @mbilalmughal can you confirm these changes are supposed to be global? (If they are, does that need to apply to buttons too? The transition on some of these are different, even now - the Enroll Now buttons on the course about pages transition to white and the Create Account transitions to black, for instance.)
> 
> > 28. When enrolled into a course with multiple enrollment dates, the course about page should display "July 15, 2023 - Enrolled" in green text rather than "Starts July 15, 2023 - Enrolled" or "Started July 15, 2023 - Enrolled".
> > 29. When a course is associated with a program, the text on the course about page "Part of the following program" should not be bold.
> 
> Where are these? The only mockups that are part of this PR in the Figma design are under "Missing Pages" - if these are updated elsewhere then we can take care of them in a separate issue.



@jkachel Sorry for the delay, I wanted to verify a few things myself and fix a few issues mentioned above.

> > 5. I would confirm if this behavior is expected, but the mock-ups show the Sign in "card" floating above the header when you scroll down on the page.

Yes, it was a small issue. The content is supposed to go under the nav, not above it. I have fixed it. Also, the nav should remain sticky on all pages throughout the site. 

2ndly I have made the secondary 'blue title bar' sticky on the desktop only. As for mobile, we shouldn't make the blue title bar sticky to save space. "Only the navigation bar remains sticky throughout desktop or mobile. ([reference](https://www.figma.com/proto/Gs4zIhOFv5gVvafawwl6PF/MITx-Online?page-id=4399%3A3891&type=design&node-id=4404-2034&viewport=441%2C157%2C0.07&t=eRWnCnJnKIDRxxIH-1&scaling=min-zoom&mode=design))

> > 7. The background (light blue) on the catalog page does not extend to the top of the footer.

- There could be two solutions to that problem:

  - Change the body color instead of adding a div and assign that grey color. It's the reason the color is not going all the way. If you are going with that approach, assign the div height in vh, e.g., height: 100vh;.

  - Another solution is to resolve the problem under a check/condition. You can change the body color to grey. As far as I know, in the course detail pages, we are using a white body background. so we can't globally change the background color to grey.

  - The third solution could be to change the grey div background position from static to fixed or absolute so it could go all the way. However, you have to check, as it might break a few other things.

> > 19. The background color of the profile page should be blue.

Yep, somehow you are using a different grey shade, please can you use #F0F5F7  
image

> >Not real sure about these since these are changes on pages that aren't in the mockup. @mbilalmughal can you confirm these changes are supposed to be global? (If they are, does that need to apply to buttons too? The transition on some of these are different, even now - the Enroll Now buttons on the course about pages transition to white and the Create Account transitions to black, for instance.)

I agree, James. There were a few inconsistencies that we should point out and fix, either on Figma or in development. I am happy to update the Figma files to help make things consistent. Regarding the white-to-red transition on the enrollment button in the course about page, I was also surprised to see it because I never created that. :D ([reference](https://www.figma.com/proto/Gs4zIhOFv5gVvafawwl6PF/MITx-Online?page-id=0%3A1&type=design&node-id=1373-5098&viewport=-2847%2C471%2C0.18&t=Hq8Mq5XqxrJiiOPg-1&scaling=min-zoom&mode=design))

**Comment by jkachel** [comment]
https://github.com/mitodl/mitxonline/pull/2119/commits/833d0a9f74b2aeb89df1f3b697854c6359eaa2de includes these styling updates:

- The default background color is now #f0f5f7 (yes, this is global, we override it for the product pages - everywhere else it looks OK)
   - This also seems to have fixed the issue on the catalog page? I made no changes but I couldn't tell (with tool assistance) that there was a color change anymore.
- I updated the widths on the inner parts of the course info box - as noted by @mbilalmughal the width of the video-js container was off and it turned out the data part of it was also too big, so everything should be aligned now.
- The top page title blue bar is now sticky on widths > 767px

We still have some mismatches - on purpose or not, not sure - for link color and button colors w/ hover; I'm inclined to punt those to a new PR since they're more global changes and get this one out sooner. I do still need to run through the list again to make sure I haven't missed anything before this is ready for re-review, but it's pretty close at least.

**Comment by jkachel** [comment]
https://github.com/mitodl/mitxonline/pull/2119/commits/13c6700fc08f3e6fb8a8b736d0226a2101c93587 has the last round of changes in it  - @collinpreston I think this is good to review now.

These are the items that I'm punting on for this PR: 

30. Screen readers are not properly reading error messages for the email field on the sign in page.
   > Move to a new issue: we use the browser-supplied validation messages for required fields in the app (in general, not just here). For whatever reason these don't get read by VoiceOver? You get the "invalid data" message but nothing else. We can switch these over to use in-app validation messages (and we generally have implemented Yup schemas for this) but this will be a bigger change that might(?) require some additional design work for the error messages themselves.

10. Hovering on the "Explore Courses" button on the home page should transition the button color to blue.
11. Hovering on the "View MITx Online Catalog" should transition the button color to blue and text color to white.
   > Not sure about these - I want to say these are different colors for a reason?

12. Should the course cards listed on the MITx Online home page be darker when not hovered on?
   > Doesn't appear to be the case - they're not on RC or prod

9. Should clicking the "browse our courses" link on the dashboard page, when not enrolled in any courses, redirect you to the main MITx Online page or the catalog page?  Currently, it redirects to the main MITx Online page.  The mock-ups show appear to indicate it should redirect to the main page as well, but I would've imagined it would redirect to the catalog page.
   > Not sure about this - it's always gone to the homepage but that predates us having a catalog. @pdpinch can maybe weigh in here? This can be a separate PR too.

25. the "Payment deadline" text color on the course about page does not appear to be the same color as the mock-ups.
26. The "Instructor-paced" text and background should be updated to match the mock-ups.
27. When a course is associated with a program, the text indicating which program the course belongs to on the course about page should not be red.
28. When enrolled into a course with multiple enrollment dates, the course about page should display "July 15, 2023 - Enrolled" in green text rather than "Starts July 15, 2023 - Enrolled" or "Started July 15, 2023 - Enrolled".
29. When a course is associated with a program, the text on the course about page "Part of the following program" should not be bold.
   > These are all on the product page so they're kinda out of scope for this - I will add them to a new issue.

**Review by collinpreston — COMMENTED** [review]
Here is what I still notice:
1. The Email field, on the sign in page, should have a dark black border when hovered.
2. Font size of the "Continue" button, on the sign in page, is incorrect.
3. Honor Code, Terms of Service and Privacy Policy links on the create-account page should turn red and have no underline when hovered.
4. The Email field, on the create-account page, should have a dark black border when hovered.
5. Font size of the "Continue" button, on the create-account page, is incorrect.
6. The "Success! We've verified your email. Please finish your account creation below.", which is displayed after clicking the email verification link when creating an account, should have a green background color.
7. Font size of the "Continue" button, on the create-account details page, is incorrect.
8. The fields on the create-account details page should have a dark black border when hovered.
9. The mock-up of the create-account details page shows the text "Already have an MITx Online account?" followed by a link to the privacy policy page.  I'm assuming the mock-up is incorrect and the privacy policy link should be replaced with the "Sign in to your account" link - which is currently functional with your branch.
10. When using a screen reader on the create-account details page, drop-down field options are not read.
11. The "Highest Level of Education" field, on the create-account additional-details page, has a red star next to the field label, however the field is not required.
12. When using a screen reader on the create-account additional-details page, the checkboxes under "Are you a?" should be announced as "Are you a student?", "Are you a Professional?", continued.  This functionality previously existed.
13. The text "Create an Account" on the create-account details page is not the correct size or weight/bold.
14. The field labels on the create-account additional-details page do not have the correct weight/bold.
15. Font size of the "Submit" button, on the create-account additional-details page, is incorrect.
16. The "browse our courses" link, displayed on the user dashboard for a user not enrolled in any courses, should turn red when hovered.
17. When focus is on the confirm password field of the account page, screen readers should read the label of the field.
18. Font size of both "Submit" buttons, on the account-settings page, are incorrect.
19. The Gender and Highest Level of Education fields on the profile page should not have a red star as they are not required.
20. Font size of the "Submit" button, on the profile page, is incorrect.
21. The header on the profile page should be ""Edit Profile" instead of "Profile Information.
22. The "Get Certificate" button shown on course cards, displayed on the dashboard page, should transition to a blue background when hovered.
23. The "Terms of service" and "Privacy policy" links on the checkout page should have red text and no underline when hovered over.
24. When attempting to purchase a course with a future start date.  The checkout page displays the course card with the text "Active from March 23, 2024 12:47 PM EDT".  The mock-ups show that this text should be " Starts March 23, 2024 12:47 PM EDT".  I'm not sure if this is related to your changes or not.
25. The "View" link on the order history page should have red text and no underline when hovered over.
26. When using a screen reader, "star" is pronounced when focused on the "Income Currency" field of the financial assistance form.
27. Font size of the "Submit request" button on the financial assistance form page is incorrect.
28. The "Submit request" button on the financial assistance form page should have a blue background when hovered.

Just to keep track, we should create some new issues that address the following issues observed while testing this PR but not related:
1. Should clicking the "browse our courses" link on the dashboard page, when not enrolled in any courses, redirect you to the main MITx Online page or the catalog page? Currently, it redirects to the main MITx Online page. The mock-ups show appear to indicate it should redirect to the main page as well, but I would've imagined it would redirect to the catalog page.
2. The "Sign in" button in the top header should transition to having a blue color and white text when hovered over.
3. When using a screen reader on the account settings page, we should announce which form the user is currently focused within.
4. The "What's the certifications track?" link on the course about page should not be red.
5. The "Payment deadline" text color on the course about page does not appear to be the same color as the mock-ups.
6. The "Instructor-paced" text and background should be updated to match the mock-ups.
7. When a course is associated with a program, the text indicating which program the course belongs to on the course about page should not be red.
8. If a program has 0 elective or 0 required courses, we are still displaying “0 Core Courses: Complete All” which could be difficult to understand from a learner’s perspective.
9. When enrolled into a course with multiple enrollment dates, the course about page should display "July 15, 2023 - Enrolled" in green text rather than "Starts July 15, 2023 - Enrolled" or "Started July 15, 2023 - Enrolled".
10. When a course is associated with a program, the text on the course about page "Part of the following program" should not be bold.

**Comment by jkachel** [comment]
https://github.com/mitodl/mitxonline/pull/2119/commits/60bf95c631e268d86101d91dbe68f8128e6c3714  should fix these: 

Other stuff - verify the forgot password flow, there are issues with form fields there too.
    Fixed - you can actually access these directly at /create-account/additional-details/ and /create-account/details/ with an existing account

1. The Email field, on the sign in page, should have a dark black border when hovered.
4. The Email field, on the create-account page, should have a dark black border when hovered.
8. The fields on the create-account details page should have a dark black border when hovered.
    Fixed


2. Font size of the "Continue" button, on the sign in page, is incorrect.
5. Font size of the "Continue" button, on the create-account page, is incorrect.
7. Font size of the "Continue" button, on the create-account details page, is incorrect.
    Fixed


27. Font size of the "Submit request" button on the financial assistance form page is incorrect.
15. Font size of the "Submit" button, on the create-account additional-details page, is incorrect.
18. Font size of both "Submit" buttons, on the account-settings page, are incorrect.
20. Font size of the "Submit" button, on the profile page, is incorrect.
    Fixed


3. Honor Code, Terms of Service and Privacy Policy links on the create-account page should turn red and have no underline when hovered.
16. The "browse our courses" link, displayed on the user dashboard for a user not enrolled in any courses, should turn red when hovered.
23. The "Terms of service" and "Privacy policy" links on the checkout page should have red text and no underline when hovered over.
25. The "View" link on the order history page should have red text and no underline when hovered over.
    Fixed


6. The "Success! We've verified your email. Please finish your account creation below.", which is displayed after clicking the email verification link when creating an account, should have a green background color.
    Fixed - also in a couple other spots (email change, password change)


9. The mock-up of the create-account details page shows the text "Already have an MITx Online account?" followed by a link to the privacy policy page.  I'm assuming the mock-up is incorrect and the privacy policy link should be replaced with the "Sign in to your account" link - which is currently functional with your branch.
    - mockup is wrong


11. The "Highest Level of Education" field, on the create-account additional-details page, has a red star next to the field label, however the field is not required.
19. The Gender and Highest Level of Education fields on the profile page should not have a red star as they are not required.
    Fixed


13. The text "Create an Account" on the create-account details page is not the correct size or weight/bold.
    Fixed (was typo)


14. The field labels on the create-account additional-details page do not have the correct weight/bold.
    Fixed


21. The header on the profile page should be ""Edit Profile" instead of "Profile Information.
    Fixed


22. The "Get Certificate" button shown on course cards, displayed on the dashboard page, should transition to a blue background when hovered.
28. The "Submit request" button on the financial assistance form page should have a blue background when hovered.
    Fixed


24. When attempting to purchase a course with a future start date.  The checkout page displays the course card with the text "Active from March 23, 2024 12:47 PM EDT".  The mock-ups show that this text should be " Starts March 23, 2024 12:47 PM EDT".  I'm not sure if this is related to your changes or not.
    Fixed (now we use the same API call that we do on the dashboard)

I also went through and checked mobile and it seems OK but we don't have mobile layouts with the updated design. Also, the Order History page on mobile is a mess; this is a longstanding issue (we punted on that a while ago and there's no design for it). 

I have not addressed any accessibility/screen reader issues but that will be next update.

**Comment by jkachel** [comment]
https://github.com/mitodl/mitxonline/pull/2119/commits/5630555df4e947e5e8e37e8e99b7941c4590fce8 fixes the screen reader issues:

17. When focus is on the confirm password field of the account page, screen readers should read the label of the field.
12. When using a screen reader on the create-account additional-details page, the checkboxes under "Are you a?" should be announced as "Are you a student?", "Are you a Professional?", continued.  This functionality previously existed.
26. When using a screen reader, "star" is pronounced when focused on the "Income Currency" field of the financial assistance form.

I had a question about this one:

10. When using a screen reader on the create-account details page, drop-down field options are not read.
    - don't understand - the options are read if I open the control, but they aren't read if the control stays closed. This seems OK to me?

I ran voiceover on the cart, financial assistance, program record, and order history pages as well and that all seems OK.

**Review by collinpreston — CHANGES_REQUESTED** [review]
1. It looks like the changes added in https://github.com/mitodl/mitxonline/pull/2011 are being displayed on the catalog page for desktop views.
2. When submitting an invalid first or last name on the create-acccount details page,  focus is automatically brought back to the invalid field but no error message is displayed.
3. The course title, "3 dot menu", and course image don't match RC when viewing the dashboard on a mobile display.  There appears to be some formatting issues.
4. The program record, when viewed on a mobile display, is missing information and formatting that is present in RC.  This could be designated to a new issue in the future.
5. Hovering over the "Allow Record Sharing", "Send Learner Record", "Share", "Revoke Sharing" buttons on the program record page will turn the background white and make the button invisible.
6. When using a screen reader on the "Send Leaner Record" pop-up modal, the "Select school" drop-down does not announce what the drop-down is being used for.  this could be designated to a new issue in the future.
7.

**Comment by jkachel** [comment]
Had a thought about the field validation and realized that "invalid" doesn't necessarily mean "empty", so tested with bad input too and still cannot reproduce:

image

**Review by collinpreston — APPROVED** [review]
Nice, this looks good to me.  We'll need to create some issues for some of the items discovered while testing this.  Would you like me to do that?

**Comment by jkachel** [comment]
I can take care of it. Thanks!

**Pull request merged**
